// ONYX FIT v0.1 — real account + cloud sync with Supabase, local fallback for alpha
import { supabase, supabaseConfigured } from './supabase-client.js';

const STORAGE='onyx_v01';
const ACCOUNT='onyx_account_v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const readDb=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')||{}}catch{return{}}};
const writeDb=db=>localStorage.setItem(STORAGE,JSON.stringify(db||{}));
const readAccount=()=>{try{return JSON.parse(localStorage.getItem(ACCOUNT)||'{}')||{}}catch{return{}}};
const writeAccount=a=>localStorage.setItem(ACCOUNT,JSON.stringify(a||{}));
let editing=false,currentUser=null;

function maskEmail(v=''){const [a,b]=String(v).split('@');if(!b)return v;return `${a.slice(0,2)}${'*'.repeat(Math.max(1,a.length-2))}@${b}`}
function setStatus(t,prefix='cloud'){const x=$(`#${prefix}Status`);if(x)x.textContent=t}
function injectAuthStyle(){if($('#onyxAuthStyle'))return;const s=document.createElement('style');s.id='onyxAuthStyle';s.textContent=`
.onyx-auth-gate{position:fixed;inset:0;z-index:20000;background:radial-gradient(circle at 50% 15%,#241106 0,#090909 38%,#050505 100%);display:grid;place-items:center;padding:max(18px,env(safe-area-inset-top)) 16px max(18px,env(safe-area-inset-bottom));overflow:auto}.onyx-auth-card{width:min(100%,440px);background:#0c0c0c;border:1px solid #292929;border-radius:24px;padding:20px;box-shadow:0 24px 70px #000}.onyx-auth-logo{font-weight:950;font-size:1.35rem;letter-spacing:.03em;margin-bottom:18px}.onyx-auth-logo b{color:#ff6500}.onyx-auth-card h1{font-size:1.8rem;margin:.2rem 0 .55rem}.onyx-auth-card label{display:block;margin:12px 0;color:#aaa;font-size:.78rem}.onyx-auth-card input{width:100%;margin-top:6px}.onyx-auth-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:14px}.onyx-auth-note{font-size:.74rem;color:#777;margin:12px 0 0}.onyx-auth-status{min-height:20px;margin-top:10px;color:#ff9a62;font-size:.8rem}@media(max-width:370px){.onyx-auth-actions{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function authForm(prefix='cloud'){return `<label>Email<input id="${prefix}Email" type="email" autocomplete="email" placeholder="toi@email.fr"></label><label>Mot de passe<input id="${prefix}Password" type="password" autocomplete="current-password" minlength="8" placeholder="8 caractères minimum"></label><div class="onyx-auth-actions"><button class="btn primary" id="${prefix}Create" type="button">CRÉER MON COMPTE</button><button class="btn" id="${prefix}Login" type="button">J’AI DÉJÀ UN COMPTE</button></div><div id="${prefix}Status" class="onyx-auth-status"></div>`}
function accountEmail(){return currentUser?.email||readAccount().email||''}
function statusHTML(){const email=accountEmail();if(email)return `<div class="card"><div class="eyebrow">COMPTE ONYX</div><h2>${maskEmail(email)}</h2><p class="muted">${supabaseConfigured?'Compte cloud actif. Tes données peuvent être synchronisées entre tes appareils.':'Mode alpha local : configure Supabase pour activer la vraie synchronisation multi-appareils.'}</p><div class="grid2"><button class="btn" id="cloudSyncNow">SYNCHRONISER</button><button class="btn ghost" id="cloudLogout">SE DÉCONNECTER</button></div><div id="cloudStatus" class="muted" style="margin-top:10px"></div></div>`;return `<div class="card"><div class="eyebrow">COMPTE ONYX</div><h2>Créer un compte ou se connecter</h2><p class="muted">Retrouve ensuite tes séances, programmes, nutrition et progression sur tous tes appareils.</p>${authForm('cloud')}</div>`}
function showGate(){if(accountEmail()||$('#onyxAuthGate'))return;injectAuthStyle();const g=document.createElement('div');g.id='onyxAuthGate';g.className='onyx-auth-gate';g.innerHTML=`<div class="onyx-auth-card"><div class="onyx-auth-logo">◢ ONYX <b>FIT</b></div><div class="eyebrow">BIENVENUE</div><h1>Ton compte ONYX</h1><p class="muted">Crée ton compte ou connecte-toi avant de configurer ton profil.</p>${authForm('gate')}<p class="onyx-auth-note">${supabaseConfigured?'Connexion sécurisée Supabase.':'Mode alpha local tant que Supabase n’est pas configuré.'}</p></div>`;document.body.appendChild(g);bindAuth('gate')}
function closeGate(){$('#onyxAuthGate')?.remove()}
async function refreshSession(){if(!supabaseConfigured||!supabase)return null;const {data}=await supabase.auth.getSession();currentUser=data?.session?.user||null;if(currentUser)writeAccount({email:currentUser.email,userId:currentUser.id,mode:'supabase',lastLogin:new Date().toISOString()});return currentUser}
async function signUp(prefix='cloud'){const email=$(`#${prefix}Email`)?.value.trim().toLowerCase(),password=$(`#${prefix}Password`)?.value||'';if(!email||!email.includes('@'))return setStatus('Entre une adresse email valide.',prefix);if(password.length<8)return setStatus('Le mot de passe doit faire au moins 8 caractères.',prefix);if(!supabaseConfigured||!supabase){writeAccount({email,mode:'local-preprod',createdAt:new Date().toISOString()});setStatus('Compte alpha local créé.',prefix);closeGate();return}setStatus('Création du compte…',prefix);const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}});if(error)return setStatus(error.message,prefix);currentUser=data?.user||null;if(currentUser)writeAccount({email:currentUser.email,userId:currentUser.id,mode:'supabase',createdAt:new Date().toISOString()});if(data?.session){await sync('push');closeGate();setStatus('Compte créé et connecté.',prefix)}else setStatus('Compte créé. Vérifie ton email pour confirmer ton adresse.',prefix)}
async function signIn(prefix='cloud'){const email=$(`#${prefix}Email`)?.value.trim().toLowerCase(),password=$(`#${prefix}Password`)?.value||'';if(!email||!email.includes('@'))return setStatus('Entre une adresse email valide.',prefix);if(password.length<8)return setStatus('Le mot de passe doit faire au moins 8 caractères.',prefix);if(!supabaseConfigured||!supabase){writeAccount({email,mode:'local-preprod',createdAt:new Date().toISOString()});setStatus('Connexion alpha locale enregistrée.',prefix);closeGate();return}setStatus('Connexion…',prefix);const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)return setStatus(error.message,prefix);currentUser=data?.user||null;if(currentUser)writeAccount({email:currentUser.email,userId:currentUser.id,mode:'supabase',lastLogin:new Date().toISOString()});await sync('merge');closeGate();setStatus('Connexion réussie.',prefix)}
function bindAuth(prefix){$(`#${prefix}Create`)?.addEventListener('click',()=>signUp(prefix));$(`#${prefix}Login`)?.addEventListener('click',()=>signIn(prefix))}
async function cloudRow(){if(!supabaseConfigured||!supabase||!currentUser)return null;const {data,error}=await supabase.from('user_state').select('data,updated_at').eq('user_id',currentUser.id).maybeSingle();if(error&&error.code!=='PGRST116')throw error;return data||null}
function mergeDb(local,remote){const l=local||{},r=remote||{};const out={...r,...l};const mergeArray=(key,idFn)=>{const all=[...(Array.isArray(r[key])?r[key]:[]),...(Array.isArray(l[key])?l[key]:[])];const seen=new Set();out[key]=all.filter(x=>{const id=idFn(x);if(seen.has(id))return false;seen.add(id);return true})};mergeArray('history',x=>x?.id||`${x?.date}|${x?.workout}|${JSON.stringify(x?.sets||[])}`);mergeArray('activities',x=>x?.sourceTrainingId||x?.id||`${x?.date}|${x?.type}|${x?.duration}|${x?.kcal}`);return out}
async function sync(mode='merge'){if(!supabaseConfigured||!supabase)return setStatus('Cloud non configuré : tes données restent sauvegardées localement.');if(!currentUser)await refreshSession();if(!currentUser)return setStatus('Connecte-toi d’abord.');try{setStatus('Synchronisation…');const local=readDb(),row=await cloudRow();let payload=local;if(mode==='pull'&&row?.data)payload=row.data;else if(mode==='merge'&&row?.data)payload=mergeDb(local,row.data);if(mode!=='push'&&payload!==local)writeDb(payload);const {error}=await supabase.from('user_state').upsert({user_id:currentUser.id,data:payload},{onConflict:'user_id'});if(error)throw error;const a=readAccount();a.email=currentUser.email;a.userId=currentUser.id;a.mode='supabase';a.lastSync=new Date().toISOString();writeAccount(a);setStatus('✓ Données synchronisées.');window.dispatchEvent(new CustomEvent('onyx:cloud-synced'));return true}catch(e){console.error(e);setStatus('Synchronisation impossible. Les données locales sont conservées.');return false}}
async function logout(){if(supabaseConfigured&&supabase)await supabase.auth.signOut();currentUser=null;localStorage.removeItem(ACCOUNT);closeGate();if(editing)openAccount($('#accountTab'));setTimeout(showGate,80)}
function bind(){$('#cloudSyncNow')?.addEventListener('click',()=>sync('merge'));$('#cloudLogout')?.addEventListener('click',logout);bindAuth('cloud')}
function mount(){const screen=$('#profileScreen'),box=$('#profileBox');if(!screen||!box||editing)return;const tabs=$('.profile-tabs');if(!tabs)return;if(!$('#accountTab')){const b=document.createElement('button');b.className='chip';b.id='accountTab';b.textContent='Compte';tabs.appendChild(b);b.onclick=()=>openAccount(b)}}
function openAccount(btn){editing=true;$$('.profile-tabs .chip').forEach(x=>x.classList.remove('on'));btn?.classList.add('on');const box=$('#profileBox');if(!box)return;box.innerHTML=statusHTML();bind()}
const obs=new MutationObserver(()=>{if(!editing)mount();if(editing&&!$('#profileScreen'))editing=false});obs.observe(document.documentElement,{childList:true,subtree:true});
async function boot(){if(supabaseConfigured&&supabase){await refreshSession();supabase.auth.onAuthStateChange((_event,session)=>{currentUser=session?.user||null;if(currentUser)writeAccount({email:currentUser.email,userId:currentUser.id,mode:'supabase',lastLogin:new Date().toISOString()});else if(readAccount().mode==='supabase')localStorage.removeItem(ACCOUNT)})}setTimeout(mount,120);setTimeout(showGate,180)}
window.addEventListener('DOMContentLoaded',boot);setTimeout(boot,420);
window.OnyxAccount={sync,configured:()=>supabaseConfigured,account:readAccount,showGate,logout};
