// ONYX FIT v0.1 — account + cloud sync foundation (Supabase-ready)
const STORAGE='onyx_v01';
const ACCOUNT='onyx_account_v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const readDb=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')||{}}catch{return{}}};
const writeDb=db=>localStorage.setItem(STORAGE,JSON.stringify(db));
const readAccount=()=>{try{return JSON.parse(localStorage.getItem(ACCOUNT)||'{}')||{}}catch{return{}}};
const writeAccount=a=>localStorage.setItem(ACCOUNT,JSON.stringify(a));
const config=window.ONYX_SUPABASE||{};
const configured=()=>!!(config.url&&config.anonKey);
let editing=false;
function maskEmail(v=''){const [a,b]=String(v).split('@');if(!b)return v;return `${a.slice(0,2)}${'*'.repeat(Math.max(1,a.length-2))}@${b}`}
function statusHTML(){const a=readAccount();if(a.email)return `<div class="card"><div class="eyebrow">COMPTE ONYX</div><h2>${maskEmail(a.email)}</h2><p class="muted">${configured()?'Synchronisation cloud prête à être activée.':'Compte local de préproduction. Le cloud sera activé dès que les clés Supabase seront configurées.'}</p><div class="grid2"><button class="btn" id="cloudSyncNow">SYNCHRONISER</button><button class="btn ghost" id="cloudLogout">SE DÉCONNECTER</button></div><div id="cloudStatus" class="muted" style="margin-top:10px"></div></div>`;return `<div class="card"><div class="eyebrow">COMPTE ONYX</div><h2>Créer ton compte</h2><p class="muted">Ton compte servira à retrouver tes séances, programmes, nutrition et progression sur tous tes appareils.</p><label>Email<input id="cloudEmail" type="email" autocomplete="email" placeholder="toi@email.fr"></label><label>Mot de passe<input id="cloudPassword" type="password" autocomplete="new-password" minlength="8" placeholder="8 caractères minimum"></label><div class="grid2"><button class="btn primary" id="cloudCreate">CRÉER LE COMPTE</button><button class="btn" id="cloudLogin">CONNEXION</button></div><p class="muted" style="margin-top:10px">Apple/Google seront ajoutés avec le backend d’authentification.</p><div id="cloudStatus" class="muted"></div></div>`}
function mount(){const screen=$('#profileScreen'),box=$('#profileBox');if(!screen||!box||editing)return;const tabs=$('.profile-tabs');if(!tabs)return;if(!$('#accountTab')){const b=document.createElement('button');b.className='chip';b.id='accountTab';b.textContent='Compte';tabs.appendChild(b);b.onclick=()=>openAccount(b)}}
function openAccount(btn){editing=true;$$('.profile-tabs .chip').forEach(x=>x.classList.remove('on'));btn?.classList.add('on');const box=$('#profileBox');if(!box)return;box.innerHTML=statusHTML();bind()}
function setStatus(t){const x=$('#cloudStatus');if(x)x.textContent=t}
function localAuth(mode){const email=$('#cloudEmail')?.value.trim().toLowerCase(),password=$('#cloudPassword')?.value||'';if(!email||!email.includes('@'))return setStatus('Entre une adresse email valide.');if(password.length<8)return setStatus('Le mot de passe doit faire au moins 8 caractères.');writeAccount({email,mode:'local-preprod',createdAt:new Date().toISOString()});setStatus(mode==='create'?'Compte de préproduction créé sur cet appareil.':'Connexion de préproduction enregistrée.');setTimeout(()=>openAccount($('#accountTab')),500)}
async function sync(){const a=readAccount();if(!a.email)return setStatus('Connecte-toi d’abord.');if(!configured())return setStatus('Cloud non configuré pour l’instant. Tes données restent sauvegardées localement sans perte.');const db=readDb();try{const r=await fetch(`${config.url}/rest/v1/onyx_user_data?on_conflict=user_email`,{method:'POST',headers:{apikey:config.anonKey,Authorization:`Bearer ${config.anonKey}`,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_email:a.email,payload:db,updated_at:new Date().toISOString()})});if(!r.ok)throw new Error(`HTTP ${r.status}`);a.lastSync=new Date().toISOString();writeAccount(a);setStatus('✓ Données synchronisées.')}catch(e){console.error(e);setStatus('Synchronisation impossible. Les données locales sont conservées.') }}
function bind(){ $('#cloudCreate')?.addEventListener('click',()=>localAuth('create'));$('#cloudLogin')?.addEventListener('click',()=>localAuth('login'));$('#cloudSyncNow')?.addEventListener('click',sync);$('#cloudLogout')?.addEventListener('click',()=>{localStorage.removeItem(ACCOUNT);openAccount($('#accountTab'))}) }
const obs=new MutationObserver(()=>{if(!editing)mount();if(editing&&!$('#profileScreen'))editing=false});obs.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('DOMContentLoaded',()=>setTimeout(mount,160));setTimeout(mount,320);
window.OnyxAccount={sync,configured,account:readAccount};
