// ONYX FIT v0.1 — real account + cloud sync with Supabase
import { supabase, supabaseConfigured } from './supabase-client.js';

const STORAGE='onyx_v01';
const ACCOUNT='onyx_account_v1';
const APP_URL='https://fazo721.github.io/ONYX-FIT-V0.1/';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const readDb=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')||{}}catch{return{}}};
const writeDb=db=>localStorage.setItem(STORAGE,JSON.stringify(db||{}));
const readAccount=()=>{try{return JSON.parse(localStorage.getItem(ACCOUNT)||'{}')||{}}catch{return{}}};
const writeAccount=a=>localStorage.setItem(ACCOUNT,JSON.stringify(a||{}));
let editing=false,currentUser=null,gateMode='choice';

function maskEmail(v=''){const [a,b]=String(v).split('@');if(!b)return v;return `${a.slice(0,2)}${'*'.repeat(Math.max(1,a.length-2))}@${b}`}
function setStatus(t,prefix='cloud',kind='info'){const x=$(`#${prefix}Status`);if(x){x.textContent=t;x.dataset.kind=kind}}
function friendlyError(error){const msg=String(error?.message||error||'');if(/invalid login credentials/i.test(msg))return 'Adresse e-mail ou mot de passe incorrect.';if(/email not confirmed/i.test(msg))return 'Ton adresse e-mail n’est pas encore confirmée.';if(/user already registered/i.test(msg))return 'Un compte existe déjà avec cette adresse e-mail.';if(/password.*least/i.test(msg))return 'Choisis un mot de passe d’au moins 8 caractères.';if(/rate limit/i.test(msg))return 'Trop de tentatives. Réessaie dans quelques minutes.';if(/network|fetch/i.test(msg))return 'Connexion impossible. Vérifie ta connexion internet.';return msg||'Une erreur est survenue.'}
function injectAuthStyle(){if($('#onyxAuthStyle'))return;const s=document.createElement('style');s.id='onyxAuthStyle';s.textContent=`
.onyx-auth-gate{position:fixed;inset:0;z-index:20000;background:radial-gradient(circle at 50% 12%,#241106 0,#090909 38%,#050505 100%);display:grid;place-items:center;padding:max(18px,env(safe-area-inset-top)) 16px max(18px,env(safe-area-inset-bottom));overflow:auto}.onyx-auth-card{width:min(100%,440px);background:#0c0c0c;border:1px solid #292929;border-radius:24px;padding:20px;box-shadow:0 24px 70px #000}.onyx-auth-logo{font-weight:950;font-size:1.45rem;letter-spacing:.03em;margin-bottom:18px}.onyx-auth-logo b{color:#ff6500}.onyx-auth-card h1{font-size:1.9rem;margin:.2rem 0 .55rem}.onyx-auth-card h2{font-size:1.28rem;margin:0 0 .35rem}.onyx-auth-card label{display:block;margin:12px 0;color:#aaa;font-size:.8rem}.onyx-auth-card input{width:100%;margin-top:6px;box-sizing:border-box}.onyx-auth-actions{display:grid;gap:9px;margin-top:14px}.onyx-auth-actions.two{grid-template-columns:1fr 1fr}.onyx-auth-note{font-size:.74rem;color:#777;margin:12px 0 0}.onyx-auth-status{min-height:20px;margin-top:10px;font-size:.82rem;line-height:1.35}.onyx-auth-status[data-kind="error"]{color:#ff7c7c}.onyx-auth-status[data-kind="success"]{color:#6fe3a1}.onyx-auth-status[data-kind="info"]{color:#ff9a62}.onyx-auth-choice{display:grid;gap:10px;margin-top:18px}.onyx-auth-choice .primary{font-size:1.02rem;padding:16px}.onyx-auth-choice .secondary{padding:14px}.onyx-auth-divider{display:flex;align-items:center;gap:10px;color:#666;font-size:.72rem;margin:16px 0}.onyx-auth-divider:before,.onyx-auth-divider:after{content:"";height:1px;background:#292929;flex:1}.onyx-auth-back{background:none;border:0;color:#aaa;padding:0 0 12px;font-size:.82rem}.onyx-auth-password-wrap{position:relative}.onyx-auth-password-wrap input{padding-right:62px}.onyx-auth-toggle{position:absolute;right:10px;top:37px;border:0;background:transparent;color:#aaa;font-size:.76rem}.onyx-auth-link{background:none;border:0;color:#ff8a3d;padding:8px 0;text-align:left;font-size:.8rem}.onyx-auth-confirm{border:1px solid #2d2d2d;border-radius:18px;padding:16px;margin-top:14px;background:#101010}.onyx-auth-confirm strong{display:block;margin-bottom:6px}.onyx-auth-confirm p{margin:0;color:#aaa;font-size:.82rem;line-height:1.45}.onyx-auth-ok{font-size:2.2rem;margin:4px 0 8px}.onyx-auth-small{font-size:.78rem;color:#8a8a8a;line-height:1.45}@media(max-width:370px){.onyx-auth-actions.two{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
function accountEmail(){const a=readAccount();return currentUser?.email||(a.mode==='supabase'?a.email:'')||''}
function pendingEmail(){const a=readAccount();return a.mode==='supabase-pending'?a.email||'':''}
function form(prefix,mode){const create=mode==='signup';return `<button class="onyx-auth-back" id="${prefix}Back" type="button">← Retour</button><h2>${create?'Créer mon compte':'Se connecter'}</h2><p class="muted">${create?'Crée ton compte pour sauvegarder automatiquement tes données ONYX.':'Connecte-toi pour retrouver ton programme et toute ta progression.'}</p><label>Adresse e-mail<input id="${prefix}Email" type="email" autocomplete="email" placeholder="toi@email.fr"></label><label>Mot de passe<div class="onyx-auth-password-wrap"><input id="${prefix}Password" type="password" autocomplete="${create?'new-password':'current-password'}" minlength="8" placeholder="8 caractères minimum"><button class="onyx-auth-toggle" id="${prefix}Toggle" type="button">Afficher</button></div></label>${create?'<p class="onyx-auth-note">Tu recevras un e-mail pour vérifier ton adresse avant la première connexion.</p>':`<button class="onyx-auth-link" id="${prefix}Forgot" type="button">Mot de passe oublié ?</button>`}<div class="onyx-auth-actions"><button class="btn primary" id="${prefix}${create?'Create':'Login'}" type="button">${create?'CONTINUER':'SE CONNECTER'}</button></div><div id="${prefix}Status" class="onyx-auth-status"></div>`}
function choiceHTML(){return `<div class="eyebrow">BIENVENUE</div><h1>Bienvenue sur ONYX FIT</h1><p class="muted">Ton entraînement, ta nutrition et ta progression, synchronisés sur ton compte.</p><div class="onyx-auth-choice"><button class="btn primary" id="gateChooseCreate" type="button">CRÉER UN COMPTE</button><button class="btn secondary" id="gateChooseLogin" type="button">SE CONNECTER</button></div><div class="onyx-auth-divider">Compte sécurisé</div><p class="onyx-auth-note">Tes données restent privées et associées à ton compte.</p>`}
function renderGate(){const g=$('#onyxAuthGate');if(!g)return;const card=g.querySelector('.onyx-auth-card');if(!card)return;card.innerHTML=`<div class="onyx-auth-logo">◢ ONYX <b>FIT</b></div>${gateMode==='choice'?choiceHTML():form('gate',gateMode)}`;bindGate();if(gateMode==='login'&&pendingEmail()){const e=$('#gateEmail');if(e)e.value=pendingEmail()}}
function showGate(force=false){if((accountEmail()&&!force)||$('#onyxAuthGate'))return;injectAuthStyle();const g=document.createElement('div');g.id='onyxAuthGate';g.className='onyx-auth-gate';g.innerHTML='<div class="onyx-auth-card"></div>';document.body.appendChild(g);gateMode=pendingEmail()?'login':'choice';renderGate()}
function closeGate(){$('#onyxAuthGate')?.remove()}
function bindGate(){
  $('#gateChooseCreate')?.addEventListener('click',()=>{gateMode='signup';renderGate()});
  $('#gateChooseLogin')?.addEventListener('click',()=>{gateMode='login';renderGate()});
  $('#gateBack')?.addEventListener('click',()=>{gateMode='choice';renderGate()});
  $('#gateToggle')?.addEventListener('click',()=>togglePassword('gate'));
  $('#gateCreate')?.addEventListener('click',()=>signUp('gate'));
  $('#gateLogin')?.addEventListener('click',()=>signIn('gate'));
  $('#gateForgot')?.addEventListener('click',()=>forgotPassword('gate'));
}
function togglePassword(prefix){const i=$(`#${prefix}Password`),b=$(`#${prefix}Toggle`);if(!i)return;const show=i.type==='password';i.type=show?'text':'password';if(b)b.textContent=show?'Masquer':'Afficher'}
async function refreshSession(){if(!supabaseConfigured||!supabase)return null;const {data}=await supabase.auth.getSession();currentUser=data?.session?.user||null;if(currentUser)writeAccount({email:currentUser.email,userId:currentUser.id,mode:'supabase',lastLogin:new Date().toISOString()});return currentUser}
function showConfirmed(email){injectAuthStyle();closeGate();const g=document.createElement('div');g.id='onyxAuthGate';g.className='onyx-auth-gate';g.innerHTML=`<div class="onyx-auth-card"><div class="onyx-auth-logo">◢ ONYX <b>FIT</b></div><div class="onyx-auth-ok">✓</div><div class="eyebrow">COMPTE VALIDÉ</div><h1>Ton compte est prêt</h1><p class="muted">${email?`L’adresse ${maskEmail(email)} est confirmée. `:''}Tes données peuvent maintenant être synchronisées.</p><div class="onyx-auth-actions"><button class="btn primary" id="gateEnterApp" type="button">ENTRER DANS ONYX FIT</button></div></div>`;document.body.appendChild(g);$('#gateEnterApp')?.addEventListener('click',()=>closeGate())}
function showRecovery(){injectAuthStyle();closeGate();const g=document.createElement('div');g.id='onyxAuthGate';g.className='onyx-auth-gate';g.innerHTML=`<div class="onyx-auth-card"><div class="onyx-auth-logo">◢ ONYX <b>FIT</b></div><div class="eyebrow">SÉCURITÉ</div><h1>Nouveau mot de passe</h1><p class="muted">Choisis ton nouveau mot de passe pour ton compte ONYX.</p><label>Nouveau mot de passe<div class="onyx-auth-password-wrap"><input id="recoveryPassword" type="password" autocomplete="new-password" minlength="8" placeholder="8 caractères minimum"><button class="onyx-auth-toggle" id="recoveryToggle" type="button">Afficher</button></div></label><label>Confirmer le mot de passe<input id="recoveryPassword2" type="password" autocomplete="new-password" minlength="8" placeholder="Répète le mot de passe"></label><div class="onyx-auth-actions"><button class="btn primary" id="recoverySave" type="button">ENREGISTRER LE MOT DE PASSE</button></div><div id="recoveryStatus" class="onyx-auth-status"></div></div>`;document.body.appendChild(g);$('#recoveryToggle')?.addEventListener('click',()=>{const i=$('#recoveryPassword'),b=$('#recoveryToggle');const show=i.type==='password';i.type=show?'text':'password';b.textContent=show?'Masquer':'Afficher'});$('#recoverySave')?.addEventListener('click',async()=>{const p=$('#recoveryPassword')?.value||'',p2=$('#recoveryPassword2')?.value||'';if(p.length<8)return setStatus('Le mot de passe doit faire au moins 8 caractères.','recovery','error');if(p!==p2)return setStatus('Les deux mots de passe ne correspondent pas.','recovery','error');setStatus('Enregistrement…','recovery','info');const {error}=await supabase.auth.updateUser({password:p});if(error)return setStatus(friendlyError(error),'recovery','error');setStatus('Mot de passe modifié.','recovery','success');setTimeout(()=>{closeGate();showConfirmed(currentUser?.email||'')},500)})}
async function signUp(prefix='cloud'){const email=$(`#${prefix}Email`)?.value.trim().toLowerCase(),password=$(`#${prefix}Password`)?.value||'';if(!email||!email.includes('@'))return setStatus('Entre une adresse e-mail valide.',prefix,'error');if(password.length<8)return setStatus('Le mot de passe doit contenir au moins 8 caractères.',prefix,'error');if(!supabaseConfigured||!supabase)return setStatus('Le service de compte n’est pas disponible pour le moment.',prefix,'error');setStatus('Création du compte…',prefix,'info');const {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:APP_URL}});if(error)return setStatus(friendlyError(error),prefix,'error');currentUser=data?.session?.user||null;if(data?.session){writeAccount({email:data.session.user.email,userId:data.session.user.id,mode:'supabase',createdAt:new Date().toISOString()});await sync('push');showConfirmed(data.session.user.email);return}writeAccount({email,userId:data?.user?.id||'',mode:'supabase-pending',createdAt:new Date().toISOString()});const card=$('#onyxAuthGate .onyx-auth-card');if(card)card.innerHTML=`<div class="onyx-auth-logo">◢ ONYX <b>FIT</b></div><div class="eyebrow">ÉTAPE 2 SUR 2</div><h1>Vérifie ton e-mail</h1><div class="onyx-auth-confirm"><strong>${email}</strong><p>On vient de t’envoyer un lien. Ouvre l’e-mail et appuie sur « Confirmer votre adresse e-mail ». Tu reviendras ensuite automatiquement dans ONYX FIT.</p></div><div class="onyx-auth-actions"><button class="btn primary" id="gateOpenMailDone" type="button">J’AI OUVERT LE LIEN</button><button class="btn" id="gateResend" type="button">RENVOYER L’E-MAIL</button><button class="btn ghost" id="gateUseOther" type="button">CHANGER D’ADRESSE</button></div><div id="gateStatus" class="onyx-auth-status"></div>`;$('#gateOpenMailDone')?.addEventListener('click',()=>{gateMode='login';renderGate();setStatus('Si ton e-mail est confirmé, connecte-toi avec ton mot de passe.','gate','info')});$('#gateResend')?.addEventListener('click',async()=>{const {error}=await supabase.auth.resend({type:'signup',email,options:{emailRedirectTo:APP_URL}});setStatus(error?friendlyError(error):'E-mail renvoyé. Vérifie aussi les indésirables.','gate',error?'error':'success')});$('#gateUseOther')?.addEventListener('click',()=>{localStorage.removeItem(ACCOUNT);gateMode='signup';renderGate()})}
async function signIn(prefix='cloud'){const email=$(`#${prefix}Email`)?.value.trim().toLowerCase(),password=$(`#${prefix}Password`)?.value||'';if(!email||!email.includes('@'))return setStatus('Entre une adresse e-mail valide.',prefix,'error');if(password.length<8)return setStatus('Entre ton mot de passe.',prefix,'error');if(!supabaseConfigured||!supabase)return setStatus('Le service de compte n’est pas disponible.',prefix,'error');setStatus('Connexion…',prefix,'info');const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)return setStatus(friendlyError(error),prefix,'error');currentUser=data?.user||null;if(currentUser)writeAccount({email:currentUser.email,userId:currentUser.id,mode:'supabase',lastLogin:new Date().toISOString()});await sync('merge');closeGate()}
async function forgotPassword(prefix='cloud'){const email=$(`#${prefix}Email`)?.value.trim().toLowerCase();if(!email||!email.includes('@'))return setStatus('Entre d’abord ton adresse e-mail.',prefix,'error');setStatus('Envoi de l’e-mail…',prefix,'info');const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:APP_URL});setStatus(error?friendlyError(error):'E-mail envoyé. Ouvre le lien reçu pour choisir un nouveau mot de passe.',prefix,error?'error':'success')}
function statusHTML(){const email=accountEmail();if(email)return `<div class="card"><div class="eyebrow">COMPTE ONYX</div><h2>${maskEmail(email)}</h2><p class="muted">Compte connecté et synchronisation cloud active.</p><div class="grid2"><button class="btn" id="cloudSyncNow">SYNCHRONISER</button><button class="btn ghost" id="cloudLogout">SE DÉCONNECTER</button></div><div id="cloudStatus" class="muted" style="margin-top:10px"></div></div>`;return `<div class="card"><div class="eyebrow">COMPTE ONYX</div><h2>Tu n’es pas connecté</h2><p class="muted">Connecte-toi pour synchroniser tes données.</p><button class="btn primary" id="cloudOpenLogin" type="button">SE CONNECTER</button></div>`}
async function cloudRow(){if(!supabaseConfigured||!supabase||!currentUser)return null;const {data,error}=await supabase.from('user_state').select('data,updated_at').eq('user_id',currentUser.id).maybeSingle();if(error&&error.code!=='PGRST116')throw error;return data||null}
function mergeDb(local,remote){const l=local||{},r=remote||{};const out={...r,...l};const mergeArray=(key,idFn)=>{const all=[...(Array.isArray(r[key])?r[key]:[]),...(Array.isArray(l[key])?l[key]:[])];const seen=new Set();out[key]=all.filter(x=>{const id=idFn(x);if(seen.has(id))return false;seen.add(id);return true})};mergeArray('history',x=>x?.id||`${x?.date}|${x?.workout}|${JSON.stringify(x?.sets||[])}`);mergeArray('activities',x=>x?.sourceTrainingId||x?.id||`${x?.date}|${x?.type}|${x?.duration}|${x?.kcal}`);return out}
async function sync(mode='merge'){if(!supabaseConfigured||!supabase)return setStatus('Cloud non configuré : tes données restent sauvegardées localement.');if(!currentUser)await refreshSession();if(!currentUser)return setStatus('Connecte-toi d’abord.');try{setStatus('Synchronisation…');const local=readDb(),row=await cloudRow();let payload=local;if(mode==='pull'&&row?.data)payload=row.data;else if(mode==='merge'&&row?.data)payload=mergeDb(local,row.data);if(mode!=='push'&&payload!==local)writeDb(payload);const {error}=await supabase.from('user_state').upsert({user_id:currentUser.id,data:payload},{onConflict:'user_id'});if(error)throw error;const a=readAccount();a.email=currentUser.email;a.userId=currentUser.id;a.mode='supabase';a.lastSync=new Date().toISOString();writeAccount(a);setStatus('✓ Données synchronisées.');window.dispatchEvent(new CustomEvent('onyx:cloud-synced'));return true}catch(e){console.error(e);setStatus('Synchronisation impossible. Les données locales sont conservées.');return false}}
async function logout(){if(supabaseConfigured&&supabase)await supabase.auth.signOut();currentUser=null;localStorage.removeItem(ACCOUNT);closeGate();if(editing)openAccount($('#accountTab'));setTimeout(()=>showGate(true),80)}
function bind(){$('#cloudSyncNow')?.addEventListener('click',()=>sync('merge'));$('#cloudLogout')?.addEventListener('click',logout);$('#cloudOpenLogin')?.addEventListener('click',()=>{gateMode='login';showGate(true);setTimeout(()=>{gateMode='login';renderGate()},10)})}
function mount(){const screen=$('#profileScreen'),box=$('#profileBox');if(!screen||!box||editing)return;const tabs=$('.profile-tabs');if(!tabs)return;if(!$('#accountTab')){const b=document.createElement('button');b.className='chip';b.id='accountTab';b.textContent='Compte';tabs.appendChild(b);b.onclick=()=>openAccount(b)}}
function openAccount(btn){editing=true;$$('.profile-tabs .chip').forEach(x=>x.classList.remove('on'));btn?.classList.add('on');const box=$('#profileBox');if(!box)return;box.innerHTML=statusHTML();bind()}
const obs=new MutationObserver(()=>{if(!editing)mount();if(editing&&!$('#profileScreen'))editing=false});obs.observe(document.documentElement,{childList:true,subtree:true});
async function boot(){if(supabaseConfigured&&supabase){const initial=await refreshSession();supabase.auth.onAuthStateChange(async(event,session)=>{currentUser=session?.user||null;if(currentUser){writeAccount({email:currentUser.email,userId:currentUser.id,mode:'supabase',lastLogin:new Date().toISOString()});if(event==='PASSWORD_RECOVERY'){setTimeout(showRecovery,0);return}if(event==='SIGNED_IN'){await sync(initial?'merge':'push');if(location.hash||location.search){history.replaceState({},document.title,APP_URL)}if($('#onyxAuthGate'))showConfirmed(currentUser.email)}}else if(readAccount().mode==='supabase')localStorage.removeItem(ACCOUNT)});if(initial&&$('#onyxAuthGate'))closeGate()}setTimeout(mount,120);setTimeout(()=>showGate(),220)}
window.addEventListener('DOMContentLoaded',boot);setTimeout(boot,420);
window.OnyxAccount={sync,configured:()=>supabaseConfigured,account:readAccount,showGate,logout};
