import { BrowserMultiFormatReader, BarcodeFormat, DecodeHintType } from '@zxing/browser';

let controls=null, busy=false;
const $=s=>document.querySelector(s);

function style(){if($('#onyxScanStyle'))return;const e=document.createElement('style');e.id='onyxScanStyle';e.textContent=`
#onyxScan{position:fixed;inset:0;z-index:10000;background:#050505;color:#fff;display:none;overflow:hidden}#onyxScan.on{display:block}.os-video{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.os-shade{position:absolute;inset:0;background:linear-gradient(#0009,#0002 28%,#0002 68%,#000b)}.os-top{position:absolute;top:max(20px,env(safe-area-inset-top));left:18px;right:18px;display:flex;align-items:center;justify-content:space-between;z-index:3}.os-title b{display:block;color:#ff6500;letter-spacing:.16em;font-size:.78rem}.os-title span{font-size:.7rem;color:#bbb}.os-close{width:48px;height:48px;border-radius:50%;border:1px solid #555;background:#111d;color:white;font-size:1.5rem}.os-frame{position:absolute;left:7%;right:7%;top:36%;height:25%;border:3px solid #ff6500;border-radius:22px;box-shadow:0 0 30px #ff650055,inset 0 0 20px #0008;z-index:2}.os-frame:before{content:'';position:absolute;left:8%;right:8%;top:50%;height:2px;background:#ff6500;box-shadow:0 0 12px #ff6500;animation:osscan 1.8s ease-in-out infinite}.os-mascot{position:absolute;z-index:3;pointer-events:none;max-width:42%;max-height:34%;object-fit:contain;right:-2%;top:20%;filter:drop-shadow(0 8px 20px #000)}.os-help{position:absolute;left:24px;right:24px;bottom:max(38px,calc(env(safe-area-inset-bottom) + 22px));z-index:3;text-align:center}.os-help b{display:block;font-size:1.05rem}.os-help span{display:block;color:#aaa;font-size:.78rem;margin-top:7px}.os-status{margin-top:14px;color:#ff8c48}.os-error{color:#ff8585}@keyframes osscan{0%,100%{transform:translateY(-45px);opacity:.5}50%{transform:translateY(45px);opacity:1}}
`;document.head.appendChild(e)}
function ui(){style();let r=$('#onyxScan');if(r)return r;r=document.createElement('div');r.id='onyxScan';r.innerHTML=`<video class="os-video" id="onyxScanVideo" playsinline muted></video><div class="os-shade"></div><div class="os-top"><div class="os-title"><b>ONYX SCAN</b><span>Scanner un code-barres</span></div><button class="os-close" aria-label="Fermer">×</button></div><div class="os-frame"></div><img class="os-mascot" id="onyxScanMascot" alt=""><div class="os-help"><b>Place le code-barres dans le cadre orange</b><span>La détection est automatique.</span><div class="os-status" id="onyxScanStatus"></div></div>`;document.body.appendChild(r);r.querySelector('.os-close').onclick=closeScanner;return r}
function findMascot(){const candidates=['/assets/onyx-scan.png','./assets/onyx-scan.png','/ONYX-FIT-V0.1/assets/onyx-scan.png','./assets/onyx_scan.png'];const img=$('#onyxScanMascot');let i=0;const next=()=>{if(i>=candidates.length){img.style.display='none';return}img.src=candidates[i++];img.onload=()=>img.style.display='block';img.onerror=next};next()}
async function closeScanner(){try{controls?.stop()}catch{}controls=null;const v=$('#onyxScanVideo');if(v?.srcObject)v.srcObject.getTracks().forEach(t=>t.stop());$('#onyxScan')?.classList.remove('on');busy=false}
async function openScanner(){const root=ui();root.classList.add('on');findMascot();const status=$('#onyxScanStatus');status.className='os-status';status.textContent='Activation de la caméra…';try{const hints=new Map();hints.set(DecodeHintType.POSSIBLE_FORMATS,[BarcodeFormat.EAN_13,BarcodeFormat.EAN_8,BarcodeFormat.UPC_A,BarcodeFormat.UPC_E,BarcodeFormat.CODE_128]);const reader=new BrowserMultiFormatReader(hints);controls=await reader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:'environment'}}},$('#onyxScanVideo'),async(result)=>{if(!result||busy)return;busy=true;const code=result.getText();status.textContent=`Code détecté : ${code}`;try{controls?.stop()}catch{}await product(code);});status.textContent='Caméra prête';}catch(e){status.className='os-status os-error';status.textContent='Caméra inaccessible. Autorise la caméra dans les réglages du navigateur.'}}
async function product(code){const status=$('#onyxScanStatus');try{const r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(code)}.json`);const j=await r.json();if(!j.product)throw new Error();sessionStorage.setItem('onyx_scanned_barcode',code);sessionStorage.setItem('onyx_scanned_product',JSON.stringify(j.product));await closeScanner();document.dispatchEvent(new CustomEvent('onyx:barcode-product',{detail:{code,product:j.product}}));}catch{busy=false;status.className='os-status os-error';status.textContent='Produit non trouvé. Essaie à nouveau.';setTimeout(()=>{if($('#onyxScan')?.classList.contains('on')){closeScanner().then(openScanner)}},900)}}
function install(){document.addEventListener('click',e=>{const b=e.target.closest('#nutScanBtn,[data-onyx-scan]');if(b){e.preventDefault();openScanner()}});document.addEventListener('onyx:barcode-product',e=>{const input=$('#nutBarcode');if(input){input.value=e.detail.code;$('#nutBarcodeBtn')?.click()}})}
install();window.onyxBarcodeScanner={open:openScanner,close:closeScanner};
