import { BrowserMultiFormatReader, BarcodeFormat, DecodeHintType } from '@zxing/browser';

let controls=null,busy=false;
const $=s=>document.querySelector(s);
const ASSET='/ONYX-FIT-V0.1/assets/onyx-scan.png.PNG';

function style(){if($('#onyxScanStyle'))return;const e=document.createElement('style');e.id='onyxScanStyle';e.textContent=`
#onyxScan{position:fixed;inset:0;z-index:20000;background:#050505;color:#fff;display:none;overflow:hidden}#onyxScan.on{display:block}.os-video{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.os-dim{position:absolute;inset:0;background:linear-gradient(#0007,#0000 18%,#0000 76%,#000a);pointer-events:none}.os-overlay{position:absolute;z-index:3;left:50%;top:50%;width:min(96vw,720px);max-height:84vh;transform:translate(-50%,-50%);object-fit:contain;pointer-events:none;filter:drop-shadow(0 16px 30px #000a)}.os-close{position:absolute;z-index:6;right:18px;top:max(18px,env(safe-area-inset-top));width:48px;height:48px;border-radius:50%;border:1px solid #555;background:#111d;color:#fff;font-size:1.7rem;display:grid;place-items:center}.os-help{position:absolute;z-index:6;left:20px;right:20px;bottom:max(26px,calc(env(safe-area-inset-bottom) + 14px));text-align:center;text-shadow:0 2px 10px #000}.os-help b{display:block;font-size:1rem}.os-help span{display:block;color:#bbb;font-size:.78rem;margin-top:6px}.os-status{margin-top:10px;color:#ff8c48;font-weight:700}.os-error{color:#ff8585}.os-success{color:#6fe3a1}.os-manual{margin-top:10px}.os-manual button{border:1px solid #484848;background:#111d;color:#fff;border-radius:999px;padding:9px 14px;font-weight:700}.os-pulse{position:absolute;z-index:4;left:14%;right:14%;top:50%;height:2px;background:#ff6500;box-shadow:0 0 18px #ff6500;animation:scanLine 1.8s ease-in-out infinite;pointer-events:none}@keyframes scanLine{0%,100%{transform:translateY(-62px);opacity:.45}50%{transform:translateY(62px);opacity:1}}@media(max-width:430px){.os-overlay{width:100vw;max-height:78vh}.os-help{bottom:max(18px,calc(env(safe-area-inset-bottom) + 10px))}}
`;document.head.appendChild(e)}
function ui(){style();let r=$('#onyxScan');if(r)return r;r=document.createElement('div');r.id='onyxScan';r.innerHTML=`<video class="os-video" id="onyxScanVideo" playsinline muted></video><div class="os-dim"></div><img class="os-overlay" id="onyxScanOverlay" src="${ASSET}" alt="Cadre Onyx Scan"><div class="os-pulse"></div><button class="os-close" aria-label="Fermer">×</button><div class="os-help"><b>Place le code-barres dans le cadre</b><span>La détection est automatique.</span><div class="os-status" id="onyxScanStatus"></div><div class="os-manual"><button type="button" id="onyxScanManual">SAISIR LE CODE</button></div></div>`;document.body.appendChild(r);r.querySelector('.os-close').onclick=closeScanner;r.querySelector('#onyxScanManual').onclick=()=>{closeScanner();setTimeout(()=>$('#nutBarcode')?.focus(),120)};return r}
async function closeScanner(){try{controls?.stop()}catch{}controls=null;const v=$('#onyxScanVideo');if(v?.srcObject)v.srcObject.getTracks().forEach(t=>t.stop());$('#onyxScan')?.classList.remove('on');busy=false;document.body.style.overflow=''}
async function openScanner(){const root=ui();root.classList.add('on');document.body.style.overflow='hidden';const status=$('#onyxScanStatus');status.className='os-status';status.textContent='Activation de la caméra…';try{const hints=new Map();hints.set(DecodeHintType.POSSIBLE_FORMATS,[BarcodeFormat.EAN_13,BarcodeFormat.EAN_8,BarcodeFormat.UPC_A,BarcodeFormat.UPC_E,BarcodeFormat.CODE_128]);const reader=new BrowserMultiFormatReader(hints);controls=await reader.decodeFromConstraints({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}}},$('#onyxScanVideo'),async(result)=>{if(!result||busy)return;busy=true;const code=result.getText();status.className='os-status os-success';status.textContent=`Code détecté : ${code}`;try{controls?.stop()}catch{}await product(code)});status.textContent='Caméra prête';}catch(e){console.error(e);status.className='os-status os-error';status.textContent='Caméra inaccessible. Autorise la caméra pour ONYX FIT.'}}
async function product(code){const status=$('#onyxScanStatus');try{status.textContent='Produit détecté, recherche…';const r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(code)}.json`);const j=await r.json();if(!j.product)throw new Error('Produit introuvable');sessionStorage.setItem('onyx_scanned_barcode',code);sessionStorage.setItem('onyx_scanned_product',JSON.stringify(j.product));await closeScanner();document.dispatchEvent(new CustomEvent('onyx:barcode-product',{detail:{code,product:j.product}}));}catch(e){busy=false;status.className='os-status os-error';status.textContent=e?.message||'Produit non trouvé. Essaie à nouveau.';setTimeout(()=>{if($('#onyxScan')?.classList.contains('on')){try{openScanner()}catch{}}},1100)}}
function install(){document.addEventListener('click',e=>{const b=e.target.closest('#nutScanBtn,[data-onyx-scan]');if(b){e.preventDefault();openScanner()}});document.addEventListener('onyx:barcode-product',e=>{const input=$('#nutBarcode');if(input){input.value=e.detail.code;$('#nutBarcodeBtn')?.click()}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&$('#onyxScan')?.classList.contains('on'))closeScanner()})}
install();window.onyxBarcodeScanner={open:openScanner,close:closeScanner};
