// ONYX FIT v0.1 — exercise library shared by program editor and technique screen
const E=[
{id:'bench_db',name:'Développé couché haltères',group:'Pecs / Triceps',muscles:['chest','triceps','frontShoulder'],setup:'Omoplates serrées et abaissées, pieds ancrés, haltères au-dessus des pectoraux.',cues:['Descends sous contrôle jusqu’à une amplitude confortable','Garde les avant-bras presque verticaux','Pousse sans laisser les épaules partir vers l’avant'],errors:['Coudes trop ouverts','Épaules qui roulent vers l’avant','Rebond ou amplitude forcée']},
{id:'bench_bar',name:'Développé couché barre',group:'Pecs / Triceps',muscles:['chest','triceps','frontShoulder'],setup:'Omoplates serrées, pieds solides au sol, prise stable et poignets neutres.',cues:['Descends vers le bas des pectoraux','Garde les avant-bras verticaux','Pousse en gardant le haut du dos verrouillé'],errors:['Barre vers le cou','Rebond sur la poitrine','Fesses qui décollent']},
{id:'incline_db',name:'Développé incliné haltères',group:'Pecs / Triceps',muscles:['upperChest','triceps','frontShoulder'],setup:'Banc légèrement incliné, omoplates serrées, pieds stables.',cues:['Descends de chaque côté du haut des pectoraux','Poignets au-dessus des coudes','Pousse sans décoller les épaules'],errors:['Inclinaison trop forte','Coudes trop ouverts','Dos qui se décolle excessivement']},
{id:'pushup',name:'Pompes',group:'Pecs / Triceps',muscles:['chest','triceps','frontShoulder'],setup:'Mains légèrement plus larges que les épaules, corps gainé de la tête aux talons.',cues:['Descends la poitrine entre les mains','Coudes à environ 30–45° du buste','Pousse le sol en gardant le bassin stable'],errors:['Bassin qui tombe','Coudes complètement écartés','Amplitude raccourcie']},
{id:'fly_db',name:'Écarté haltères',group:'Pecs',muscles:['chest'],setup:'Omoplates fixées, coudes légèrement fléchis, haltères au-dessus des pectoraux.',cues:['Ouvre en arc de cercle','Garde la même légère flexion du coude','Ramène avec les pectoraux sans cogner les haltères'],errors:['Descendre trop bas','Transformer en développé','Épaules vers l’avant']},
{id:'lat_pull',name:'Tirage vertical poulie',group:'Dos / Biceps',muscles:['lats','biceps','upperBack'],setup:'Poitrine haute, bassin stable, épaules basses.',cues:['Tire avec les coudes','Amène la barre vers le haut du torse','Contrôle complètement la remontée'],errors:['Tirer derrière la nuque','Se balancer fortement','Épaules qui montent']},
{id:'row_db',name:'Rowing haltère',group:'Dos / Biceps',muscles:['lats','upperBack','biceps'],setup:'Dos neutre, abdos serrés, épaule loin de l’oreille.',cues:['Tire le coude vers la hanche','Commence par l’omoplate','Contrôle le retour complet'],errors:['Tourner tout le buste','Hausser l’épaule','Donner de l’élan avec le bas du dos']},
{id:'row_cable',name:'Rowing poulie basse',group:'Dos / Biceps',muscles:['lats','upperBack','biceps'],setup:'Buste stable, poitrine haute, épaules relâchées vers le bas.',cues:['Tire les coudes en arrière','Serre les omoplates sans cambrer','Rallonge les bras sous contrôle'],errors:['Se balancer','Tirer avec les épaules hautes','Arrondir fortement le dos']},
{id:'pullup',name:'Tractions',group:'Dos / Biceps',muscles:['lats','upperBack','biceps'],setup:'Prise confortable, corps gainé, épaules abaissées avant de tirer.',cues:['Pense à tirer les coudes vers les côtes','Monte la poitrine vers la barre','Redescends jusqu’à une extension contrôlée'],errors:['Kipping involontaire','Épaules dans les oreilles','Demi-amplitude']},
{id:'face_pull',name:'Face pull',group:'Épaules / Dos',muscles:['rearShoulder','upperBack'],setup:'Poulie à hauteur du visage, buste stable.',cues:['Tire vers les tempes','Écarte les mains en fin de mouvement','Serre les omoplates'],errors:['Coudes trop bas','Tirer vers la poitrine','Cambrer pour finir']},
{id:'ohp_db',name:'Développé épaules haltères',group:'Épaules / Triceps',muscles:['shoulders','triceps'],setup:'Buste gainé, côtes basses, haltères au niveau des épaules.',cues:['Pousse au-dessus de la tête','Garde les avant-bras verticaux','Redescends sous contrôle'],errors:['Cambrure excessive','Poignets cassés','Descente trop basse douloureuse']},
{id:'lat_raise',name:'Élévations latérales',group:'Épaules',muscles:['shoulders'],setup:'Épaules basses, légère flexion des coudes, buste fixe.',cues:['Monte les bras jusqu’à environ l’horizontale','Conduis avec les coudes','Redescends lentement'],errors:['Hausser les épaules','Balancer le corps','Monter beaucoup trop haut']},
{id:'curl_db',name:'Curl haltères',group:'Biceps',muscles:['biceps'],setup:'Coudes près du corps, épaules basses, buste fixe.',cues:['Plie le coude sans l’avancer','Contracte fort en haut','Redescends lentement'],errors:['Balancer le buste','Avancer les coudes','Lâcher la descente']},
{id:'curl_hammer',name:'Curl marteau',group:'Biceps',muscles:['biceps','forearms'],setup:'Prise neutre, coudes collés au corps, buste stable.',cues:['Monte sans tourner le poignet','Garde le coude fixe','Contrôle la descente'],errors:['Élan du dos','Coudes vers l’avant','Amplitude raccourcie']},
{id:'tri_push',name:'Extension triceps poulie',group:'Triceps',muscles:['triceps'],setup:'Épaules basses, coudes fixes près du buste.',cues:['Étends complètement le coude','Garde le haut du bras immobile','Contrôle le retour'],errors:['Coudes qui s’écartent','Buste qui donne de l’élan','Amplitude incomplète']},
{id:'goblet',name:'Goblet squat',group:'Jambes / Fessiers',muscles:['quads','glutes','adductors'],setup:'Pieds stables, charge contre la poitrine, genoux dans l’axe des orteils.',cues:['Descends entre les hanches','Garde tout le pied au sol','Remonte en poussant le sol'],errors:['Genoux qui rentrent','Talons qui décollent','Dos qui s’arrondit']},
{id:'squat_bar',name:'Squat barre',group:'Jambes / Fessiers',muscles:['quads','glutes','adductors'],setup:'Barre stable, tronc gainé, pieds ancrés.',cues:['Descends avec genoux et hanches ensemble','Garde les genoux dans l’axe des pieds','Pousse le sol pour remonter'],errors:['Genoux qui rentrent','Perte du gainage','Profondeur forcée']},
{id:'bulgarian',name:'Fentes bulgares',group:'Jambes / Fessiers',muscles:['quads','glutes','hamstrings'],setup:'Pied avant stable, pied arrière surélevé, bassin face devant.',cues:['Descends verticalement','Genou avant dans l’axe du pied','Pousse dans le milieu du pied avant'],errors:['Pas trop court','Genou qui s’effondre vers l’intérieur','Buste qui tombe excessivement']},
{id:'rdl',name:'Soulevé de terre roumain haltères',group:'Jambes / Fessiers',muscles:['hamstrings','glutes','back'],setup:'Dos neutre, haltères près des jambes, genoux légèrement fléchis.',cues:['Recule les hanches','Garde les charges près des cuisses','Remonte en serrant les fessiers'],errors:['Arrondir le dos','Fléchir comme un squat','Descendre au-delà de ta mobilité']},
{id:'hip_thrust',name:'Hip thrust',group:'Jambes / Fessiers',muscles:['glutes','hamstrings'],setup:'Haut du dos sur le banc, menton légèrement rentré, pieds stables.',cues:['Monte jusqu’à aligner épaules-hanches-genoux','Rétroverse légèrement le bassin en haut','Contrôle la descente'],errors:['Hyperextension lombaire','Pieds mal placés','Rebond en bas']},
{id:'leg_press',name:'Leg press',group:'Jambes / Fessiers',muscles:['quads','glutes'],setup:'Dos et bassin collés au dossier, pieds stables sur la plateforme.',cues:['Descends tant que le bassin reste stable','Genoux dans l’axe des pieds','Pousse sans verrouiller brutalement'],errors:['Bassin qui se décolle','Genoux qui rentrent','Amplitude excessive']},
{id:'calf',name:'Mollets debout',group:'Jambes',muscles:['calves'],setup:'Appuis stables, genoux souples, amplitude confortable.',cues:['Monte sur la pointe des pieds','Marque une contraction en haut','Redescends lentement'],errors:['Rebondir','Amplitude minime','Chevilles qui s’effondrent']},
{id:'plank',name:'Planche',group:'Abdos',muscles:['core'],setup:'Coudes sous les épaules, corps aligné.',cues:['Serre fessiers et abdos','Pousse les avant-bras dans le sol','Respire sans perdre la position'],errors:['Bassin trop haut','Bas du dos qui s’effondre','Tête relevée']}
];
const byName=n=>E.find(x=>x.name.toLowerCase()===String(n||'').trim().toLowerCase())||E.find(x=>String(n||'').toLowerCase().includes(x.name.toLowerCase()))||null;
window.OnyxExerciseLibrary={all:E,get:byName,groups:[...new Set(E.map(x=>x.group))]};
