import './style.css';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const EQUIPMENT=['Haltères','Banc inclinable','Poulie haute','Poulie basse','Double poulie','Barre olympique','Disques','Rack / cage','Élastiques','Kettlebells','Barre de traction','Rameur','Tapis de course','Vélo','Smith machine','Leg press','Leg extension','Leg curl','Machine pecs','Machine épaules'];
const DEFAULT={onboarded:false,profile:{name:'',sex:'male',birth:'',height:180,weight:80,fat:'',activity:'moderate',goal:'recomp',sessions:4,duration:60,focus:[],equipment:['Haltères','Banc inclinable','Poulie haute','Poulie basse']},foods:[],activities:[],body:[],program:[],history:[]};
let db=JSON.parse(localStorage.getItem('onyx_v01')||'null')||structuredClone(DEFAULT);
const save=()=>localStorage.setItem('onyx_v01',JSON.stringify(db));
const today=()=>new Date().toISOString().slice(0,10);

function mascot(state='ready'){
  const lift=state==='lift';
  return `<svg class="onyx-svg" viewBox="0 0 240 220" aria-label="Onyx"><defs><linearGradient id="f" x1="0" x2="1"><stop stop-color="#ff5a00"/><stop offset="1" stop-color="#ffb000"/></linearGradient></defs><path d="M120 8C99 41 77 28 82 61C52 43 47 86 64 109C48 145 74 180 120 192C166 180 192 145 176 109C193 86 188 43 158 61C163 28 141 41 120 8Z" fill="#111" stroke="url(#f)" stroke-width="8"/><ellipse cx="94" cy="91" rx="14" ry="18" fill="#ff7a00"/><ellipse cx="146" cy="91" rx="14" ry="18" fill="#ff7a00"/><circle cx="99" cy="86" r="4" fill="white"/><circle cx="151" cy="86" r="4" fill="white"/><path d="M109 120q11 10 22 0" fill="none" stroke="#666" stroke-width="4"/><path d="M120 136l-13 22h14l-7 21 25-31h-15l9-12z" fill="#ff6400"/>${lift?'<path d="M77 140Q40 115 42 80M163 140Q200 115 198 80" stroke="#171717" stroke-width="18" fill="none" stroke-linecap="round"/><rect x="25" y="68" width="190" height="10" rx="5" fill="#555"/>':'<path d="M78 144Q58 166 49 150M162 144Q182 166 191 150" stroke="#171717" stroke-width="18" fill="none" stroke-linecap="round"/>'}</svg>`;
}
function age(){if(!db.profile.birth)return 30;const b=new Date(db.profile.birth),n=new Date();return n.getFullYear()-b.getFullYear()-((n.getMonth()<b.getMonth()||(n.getMonth()===b.getMonth()&&n.getDate()<b.getDate()))?1:0)}
function targets(){const p=db.profile,w=+p.weight||80,h=+p.height||180,a=age();let bmr=p.sex==='female'?10*w+6.25*h-5*a-161:10*w+6.25*h-5*a+5;let mult={low:1.2,light:1.375,moderate:1.55,high:1.725,veryhigh:1.9}[p.activity]||1.55;let kcal=bmr*mult;if(p.goal==='cut')kcal-=400;if(p.goal==='muscle')kcal+=250;kcal=Math.round(kcal/10)*10;const protein=Math.round(w*(p.goal==='cut'?2:1.8)),fat=Math.round(w*.8),carbs=Math.max(0,Math.round((kcal-protein*4-fat*9)/4));return{kcal,protein,fat,carbs}}
function eaten(){return db.foods.filter(f=>f.date===today()).reduce((a,f)=>({kcal:a.kcal+f.kcal,protein:a.protein+f.protein,carbs:a.carbs+f.carbs,fat:a.fat+f.fat}),{kcal:0,protein:0,carbs:0,fat:0})}
function macroBoxes(){const n=eaten(),m=targets();return `<div class="macro">${[['Calories',n.kcal,m.kcal,'kcal'],['Protéines',n.protein,m.protein,'g'],['Glucides',n.carbs,m.carbs,'g'],['Lipides',n.fat,m.fat,'g']].map(([a,v,t,u])=>`<div><span>${a}</span><strong>${Math.round(v)}</strong> / ${t} ${u}<div class="progress"><i style="width:${Math.min(100,t?v/t*100:0)}%"></i></div></div>`).join('')}</div>`}
function generateProgram(){const p=db.profile,eq=new Set(p.equipment),cable=eq.has('Poulie haute')||eq.has('Double poulie'),bench=eq.has('Banc inclinable'),dbs=eq.has('Haltères');const upper=[dbs?'Développé couché haltères':'Pompes',cable?'Tirage vertical poulie':'Rowing haltère',bench?'Développé incliné haltères':'Développé épaules',cable?'Face pull':'Oiseau haltères','Curl haltères',cable?'Extension triceps poulie':'Extension triceps haltère'];const lower=['Goblet squat','Fentes bulgares','Soulevé de terre roumain haltères','Hip thrust','Mollets','Planche'];const out=[];for(let i=0;i<p.sessions;i++)out.push({name:i%2===0?`Haut ${Math.floor(i/2)+1}`:`Jambes ${Math.ceil(i/2)}`,exercises:(i%2===0?upper:lower).slice(0,p.duration<=45?5:6)});return out}

function render(){document.querySelector('#app').innerHTML=`<header class="top"><button class="ghost btn" id="menu">☰</button><div class="brand">◢ ONYX <b>FIT</b> <span class="version">v0.1 ALPHA</span></div><button class="ghost btn" data-nav="profile">◎</button></header><main>${home()}${workout()}${food()}${activity()}${profile()}${onboarding()}</main><nav class="bottom"><button data-nav="home" class="active">⌂<small>Accueil</small></button><button data-nav="workout">◫<small>Muscu</small></button><button data-nav="food">⌁<small>Nutrition</small></button><button data-nav="activity">⚡<small>Activité</small></button><button data-nav="profile">◎<small>Profil</small></button></nav>`;bind();nav(db.onboarded?'home':'onboarding')}
function home(){const t=targets(),n=eaten();return `<section class="screen" id="homeScreen"><div class="hero card"><div><div class="eyebrow">TON COACH ÉNERGIE</div><h1>Salut ${db.profile.name||'champion'} 🔥</h1><p class="muted">Muscu, nutrition, activité et progression au même endroit.</p><button class="btn primary big" data-nav="workout">COMMENCER LA SÉANCE</button></div><div class="mascot">${mascot()}</div></div><div class="grid3"><div class="metric"><span>Poids</span><strong>${db.profile.weight}</strong> kg</div><div class="metric"><span>Calories</span><strong>${Math.round(n.kcal)}</strong> / ${t.kcal}</div><div class="metric"><span>Séances</span><strong>${db.profile.sessions}</strong> / sem.</div></div><div class="card"><div class="sectionHead"><h2>Macros aujourd’hui</h2><span class="pill">${t.kcal} kcal cible</span></div>${macroBoxes()}</div><div class="card"><h2>Coach IA</h2><p class="muted">Prévu pour une prochaine version. La v0.1 valide d’abord les fondations.</p><button class="btn" disabled>IA bientôt</button></div></section>`}
function workout(){return `<section class="screen" id="workoutScreen"><div class="eyebrow">ENTRAÎNEMENT</div><h1>Ta séance</h1><div id="workoutBox"></div></section>`}
function food(){return `<section class="screen" id="foodScreen"><div class="eyebrow">NUTRITION</div><h1>Journal alimentaire</h1><div class="card"><h2>Produit par code-barres</h2><label>Code-barres<input id="barcode" inputmode="numeric" placeholder="3017620422003"></label><button class="btn primary" id="lookup">RECHERCHER</button><div id="product"></div></div><div class="card"><h2>Aujourd’hui</h2><div id="foodToday"></div></div><div class="card"><h2>Recettes IA</h2><button class="btn" disabled>IA bientôt</button></div></section>`}
function activity(){return `<section class="screen" id="activityScreen"><div class="eyebrow">ACTIVITÉ</div><h1>Dépense quotidienne</h1><div class="card notice"><b>Apple Santé arrive plus tard.</b><div class="muted">La v0.1 permet d’abord la saisie manuelle.</div></div><div class="card"><h2>Ajouter une activité</h2><div class="grid2"><label>Type<select id="actType"><option>Marche</option><option>Vélo</option><option>Course</option><option>Travail physique</option><option>Randonnée</option><option>Natation</option><option>Autre</option></select></label><label>Durée (min)<input id="actDuration" type="number"></label><label>Kcal brûlées<input id="actKcal" type="number"></label><label>Date<input id="actDate" type="date" value="${today()}"></label></div><button class="btn primary" id="addActivity">AJOUTER</button></div><div class="card"><h2>Historique</h2><div id="activityList"></div></div></section>`}
function profile(){const p=db.profile;return `<section class="screen" id="profileScreen"><div class="eyebrow">PROFIL</div><h1>Réglages</h1><div class="card"><div class="grid2"><label>Prénom<input id="pName" value="${p.name}"></label><label>Taille (cm)<input id="pHeight" type="number" value="${p.height}"></label><label>Poids (kg)<input id="pWeight" type="number" step=".1" value="${p.weight}"></label><label>Objectif<select id="pGoal"><option value="recomp">Recomposition</option><option value="cut">Perte de gras</option><option value="muscle">Prise de muscle</option><option value="maintain">Maintien</option></select></label></div><button class="btn primary" id="saveProfile">SAUVEGARDER</button></div><div class="card"><h2>Mon matériel</h2><div class="chips">${p.equipment.map(x=>`<span class="chip on">${x}</span>`).join('')}</div><p class="muted">La modification complète du matériel sera renforcée en v0.2.</p></div></section>`}
function onboarding(){return `<section class="screen" id="onboardingScreen"><div class="eyebrow">BIENVENUE</div><h1>Configure ONYX FIT</h1><div class="card"><h2>1. Ton profil</h2><div class="grid2"><label>Prénom<input id="oName"></label><label>Sexe biologique<select id="oSex"><option value="male">Homme</option><option value="female">Femme</option></select></label><label>Date de naissance<input id="oBirth" type="date"></label><label>Taille (cm)<input id="oHeight" type="number" value="180"></label><label>Poids (kg)<input id="oWeight" type="number" step=".1" value="80"></label><label>Masse grasse % (optionnel)<input id="oFat" type="number" step=".1"></label></div></div><div class="card"><h2>2. Objectif & rythme</h2><label>Objectif<select id="oGoal"><option value="recomp">Recomposition</option><option value="cut">Perte de gras</option><option value="muscle">Prise de muscle</option><option value="maintain">Maintien</option></select></label><label>Activité hors sport<select id="oActivity"><option value="low">Faible</option><option value="light">Légère</option><option value="moderate" selected>Modérée</option><option value="high">Élevée</option><option value="veryhigh">Très élevée</option></select></label><div class="grid2"><label>Séances / semaine<select id="oSessions"><option>2</option><option>3</option><option selected>4</option><option>5</option><option>6</option></select></label><label>Durée<select id="oDuration"><option>30</option><option>45</option><option selected>60</option><option>75</option><option>90</option></select></label></div><div class="chips" id="focusChips">${['Pectoraux','Dos','Épaules','Bras','Jambes','Fessiers','Abdos'].map(x=>`<button class="chip" data-focus="${x}">${x}</button>`).join('')}</div></div><div class="card"><h2>3. Ton home gym</h2><div class="chips" id="equipmentChips">${EQUIPMENT.map(x=>`<button class="chip" data-eq="${x}">${x}</button>`).join('')}</div></div><button class="btn primary big" id="finish">CRÉER MON PROGRAMME</button></section>`}

let ws={w:0,e:0,s:0,sets:[]};
function nav(n){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+n+'Screen')?.classList.add('active');$$('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.nav===n));if(n==='workout')renderWorkout();if(n==='food')renderFood();if(n==='activity')renderActivity()}
function renderWorkout(){if(!db.program.length)db.program=generateProgram();const w=db.program[ws.w%db.program.length],name=w.exercises[ws.e]||w.exercises[0];$('#workoutBox').innerHTML=`<div class="exercise card"><div class="sectionHead"><span class="pill">Exercice ${ws.e+1}/${w.exercises.length}</span><button class="btn" id="tech">ⓘ Technique</button></div><div class="mascot">${mascot('lift')}</div><div class="eyebrow">${w.name}</div><h1>${name}</h1><p class="muted">Série ${ws.s+1}/3</p><div class="setGrid"><label>Charge kg<input class="bigInput" id="setWeight" type="number" step=".5"></label><label>Répétitions<input class="bigInput" id="setReps" type="number"></label><label>RPE<input class="bigInput" id="setRpe" type="number" step=".5" max="10"></label></div><button class="btn primary big" id="validateSet">VALIDER LA SÉRIE</button></div>`;$('#tech').onclick=()=>alert('Les planches anatomiques spécifiques arrivent dans une prochaine version.');$('#validateSet').onclick=()=>{ws.sets.push({exercise:name,weight:+$('#setWeight').value||0,reps:+$('#setReps').value||0,rpe:+$('#setRpe').value||0});ws.s++;if(ws.s>=3){ws.s=0;ws.e++;if(ws.e>=w.exercises.length){db.history.push({date:new Date().toISOString(),workout:w.name,sets:ws.sets});ws={w:(ws.w+1)%db.program.length,e:0,s:0,sets:[]};save();alert('Séance terminée 🔥')}}renderWorkout()}}
async function lookupBarcode(){const code=$('#barcode').value.trim();if(!code)return;$('#product').innerHTML='<p class="muted">Recherche…</p>';try{const r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${encodeURIComponent(code)}.json`),j=await r.json();if(!j.product)throw new Error('Produit introuvable');const p=j.product,n=p.nutriments||{},item={name:p.product_name||'Produit',kcal:+(n['energy-kcal_100g']||0),protein:+(n.proteins_100g||0),carbs:+(n.carbohydrates_100g||0),fat:+(n.fat_100g||0)};$('#product').innerHTML=`<div class="foodRow"><b>${item.name}</b><p class="muted">Pour 100 g : ${item.kcal} kcal • P ${item.protein} • G ${item.carbs} • L ${item.fat}</p><label>Quantité mangée (g)<input id="qty" type="number" value="100"></label><button class="btn primary" id="addFood">AJOUTER</button></div>`;$('#addFood').onclick=()=>{const q=+$('#qty').value||100,k=q/100;db.foods.push({date:today(),name:item.name,qty:q,kcal:item.kcal*k,protein:item.protein*k,carbs:item.carbs*k,fat:item.fat*k});save();renderFood()}}catch(e){$('#product').innerHTML=`<p class="bad">${e.message}</p>`}}
function renderFood(){$('#foodToday').innerHTML=macroBoxes()+db.foods.filter(f=>f.date===today()).map(f=>`<div class="foodRow"><b>${f.name}</b><span style="float:right">${Math.round(f.kcal)} kcal</span><div class="muted">${f.qty} g • P ${f.protein.toFixed(1)} • G ${f.carbs.toFixed(1)} • L ${f.fat.toFixed(1)}</div></div>`).join('')}
function renderActivity(){$('#activityList').innerHTML=[...db.activities].reverse().map(a=>`<div class="row"><b>${a.type}</b><span style="float:right">${a.kcal?Math.round(a.kcal)+' kcal':''}</span><div class="muted">${a.date}${a.duration?' • '+a.duration+' min':''}</div></div>`).join('')||'<p class="muted">Aucune activité.</p>'}
function bind(){$$('[data-nav]').forEach(b=>b.onclick=()=>nav(b.dataset.nav));$('#menu').onclick=()=>nav('profile');$$('#equipmentChips .chip').forEach(b=>b.onclick=()=>b.classList.toggle('on'));$$('#focusChips .chip').forEach(b=>b.onclick=()=>b.classList.toggle('on'));$('#finish').onclick=()=>{db.profile={...db.profile,name:$('#oName').value,sex:$('#oSex').value,birth:$('#oBirth').value,height:+$('#oHeight').value,weight:+$('#oWeight').value,fat:+$('#oFat').value||'',goal:$('#oGoal').value,activity:$('#oActivity').value,sessions:+$('#oSessions').value,duration:+$('#oDuration').value,focus:$$('#focusChips .on').map(x=>x.dataset.focus),equipment:$$('#equipmentChips .on').map(x=>x.dataset.eq)};db.onboarded=true;db.body.push({date:today(),weight:db.profile.weight,fat:db.profile.fat||null});db.program=generateProgram();save();render()};$('#lookup').onclick=lookupBarcode;$('#addActivity').onclick=()=>{db.activities.push({date:$('#actDate').value,type:$('#actType').value,duration:+$('#actDuration').value||0,kcal:+$('#actKcal').value||0});save();renderActivity()};$('#saveProfile').onclick=()=>{db.profile.name=$('#pName').value;db.profile.height=+$('#pHeight').value;db.profile.weight=+$('#pWeight').value;db.profile.goal=$('#pGoal').value;db.program=generateProgram();save();alert('Profil sauvegardé')}}
render();
