// ONYX FIT v0.1 — compact advanced program editor with exercise library
const STORAGE='onyx_v01';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')||{}}catch{return{}}};
const write=db=>localStorage.setItem(STORAGE,JSON.stringify(db));
const norm=ex=>window.OnyxProgram?.normalizeExercise?window.OnyxProgram.normalizeExercise(ex):{name:typeof ex==='string'?ex:(ex?.name||'Exercice'),sets:Number(ex?.sets)||3,repMin:Number(ex?.repMin)||8,repMax:Number(ex?.repMax)||12,targetRpe:Number(ex?.targetRpe)||8,restSeconds:Number(ex?.restSeconds)||60,unit:ex?.unit||'reps'};
const library=()=>window.OnyxExerciseLibrary?.all||[];
const libMatch=name=>window.OnyxExerciseLibrary?.get?.(name)||null;
let editing=false,selectedDay=0,draft=[];
function injectEditorStyle(){if($('#programEditorCompactStyle'))return;const s=document.createElement('style');s.id='programEditorCompactStyle';s.textContent=`
.program-editor-card{overflow:hidden}.program-editor-card>label{display:block;margin:12px 0}.program-editor-card>label select{width:100%}
.program-day{margin-top:14px}.program-day-head{display:flex;gap:10px;align-items:end;justify-content:space-between;margin-bottom:12px}.program-day-head>div{flex:1;min-width:0}.program-day-head input{width:100%}
.pe-exercises{display:grid;gap:10px}.pe-exercise{background:#0a0a0a;border:1px solid #252525;border-radius:16px;padding:10px}.pe-source{display:grid;grid-template-columns:1fr auto;gap:7px;align-items:end;margin-bottom:8px}.pe-source label{font-size:.66rem;color:#8d8d8d}.pe-source select{width:100%;height:40px}.pe-custom{display:none}.pe-exercise.is-custom .pe-custom{display:block}.pe-exercise.is-library .pe-custom{display:none}.pe-lib-badge{font-size:.64rem;color:#ff965f;background:#1c1009;border:1px solid #5a2c12;border-radius:999px;padding:8px 9px;white-space:nowrap}
.pe-ex-title{display:grid;grid-template-columns:1fr 34px;gap:8px;align-items:center;margin-bottom:9px}.pe-name{width:100%;font-weight:800}.pe-name[readonly]{opacity:.9;background:#111}.pe-remove{width:34px;height:34px;border-radius:999px;border:1px solid #333;background:#161616;color:#aaa;font-size:1.1rem}
.pe-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px}.pe-grid label{min-width:0;font-size:.66rem;color:#8d8d8d}.pe-grid input,.pe-grid select{width:100%;min-width:0;height:40px;padding:7px 8px;border-radius:10px;text-align:center;font-size:.88rem}.pe-grid select{text-align:left;padding-right:22px}.pe-add-ex{width:100%;margin-top:9px}.pe-add-day{margin-top:12px}.pe-save{margin-top:8px}
@media(max-width:430px){.program-editor-card{padding:12px}.program-day-head{align-items:stretch;flex-direction:column}.program-day-head .pe-delete-day{align-self:flex-end;padding:8px 10px}.pe-grid{grid-template-columns:repeat(3,1fr);gap:6px}.pe-grid label{font-size:.6rem}.pe-grid input,.pe-grid select{height:38px;padding:6px;font-size:.8rem}.pe-grid select{font-size:.72rem}.pe-exercise{padding:9px}.pe-ex-title{grid-template-columns:1fr 32px}.pe-remove{width:32px;height:32px}.pe-source{grid-template-columns:1fr}.pe-lib-badge{justify-self:start}}
@media(max-width:345px){.pe-grid{grid-template-columns:repeat(2,1fr)}}
`;document.head.appendChild(s)}
function program(){const db=read();return Array.isArray(db.program)?db.program:[]}
function cloneProgram(){return program().map((w,i)=>({name:w?.name||`Séance ${i+1}`,exercises:(Array.isArray(w?.exercises)?w.exercises:[]).map(norm)}))}
function groupScore(name){const n=String(name||'').toLowerCase();const s={Pecs:0,Dos:0,Épaules:0,Biceps:0,Triceps:0,Jambes:0,Fessiers:0,Abdos:0};if(/développé couché|developpe couche|développé incliné|developpe incline|pompe|pec|chest|écarté|ecarte/.test(n))s.Pecs+=3;if(/rowing|tirage|traction|pulldown|dors|dos|face pull/.test(n))s.Dos+=3;if(/épaule|epaule|élévation|elevation|oiseau|militaire|shoulder|face pull/.test(n))s.Épaules+=2;if(/curl|biceps/.test(n))s.Biceps+=3;if(/triceps|extension triceps|barre au front|dips/.test(n))s.Triceps+=3;if(/squat|fente|bulgare|leg press|leg extension|leg curl|mollet|soulevé de terre|souleve de terre/.test(n))s.Jambes+=3;if(/hip thrust|fessier|glute|bulgare/.test(n))s.Fessiers+=2;if(/abdo|planche|gainage|crunch/.test(n))s.AbdoS+=3;return s}
function inferredName(w,idx){const totals={Pecs:0,Dos:0,Épaules:0,Biceps:0,Triceps:0,Jambes:0,Fessiers:0,Abdos:0};(w?.exercises||[]).forEach(ex=>{const sc=groupScore(ex?.name||ex);Object.keys(totals).forEach(k=>totals[k]+=sc[k]||0)});const ranked=Object.entries(totals).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]);if(!ranked.length)return `Séance ${idx+1}`;const a=ranked[0]?.[0],b=ranked[1]?.[0];return (a==='Pecs'&&b==='Triceps')||(a==='Triceps'&&b==='Pecs')?'Pecs / Triceps':(a==='Dos'&&b==='Biceps')||(a==='Biceps'&&b==='Dos')?'Dos / Biceps':(a==='Jambes'&&b==='Fessiers')||(a==='Fessiers'&&b==='Jambes')?'Jambes / Fessiers':b&&ranked[1][1]>=Math.max(2,ranked[0][1]*.45)?`${a} / ${b}`:a}
function autoNameAll(){draft.forEach((w,i)=>{w.name=inferredName(w,i)})}
function editorHTML(){draft=cloneProgram();autoNameAll();selectedDay=Math.min(selectedDay,Math.max(0,draft.length-1));return `<div class="card program-editor-card"><div class="program-editor-head"><div><div class="eyebrow">PROGRAMME ACTUEL</div><h2>Modifier mon programme</h2><p class="muted">Choisis les exercices dans la bibliothèque pour profiter des fiches techniques et de l’anatomie. Tu peux aussi garder un exercice libre.</p></div></div>${draft.length?`<label>SÉANCE À MODIFIER<select id="peDaySelect">${draft.map((w,i)=>`<option value="${i}" ${i===selectedDay?'selected':''}>${esc(w.name||inferredName(w,i))}</option>`).join('')}</select></label><div id="peDayHost">${dayHTML(selectedDay)}</div><button class="btn pe-add-day full">+ AJOUTER UNE SÉANCE</button><button class="btn primary big full pe-save">ENREGISTRER LE PROGRAMME</button>`:`<p class="muted">Aucun programme. Crée d’abord un programme automatique puis personnalise-le ici.</p>`}</div>`}
function dayHTML(i){const w=draft[i];if(!w)return'';return `<section class="program-day" data-day="${i}"><div class="program-day-head"><div><div class="eyebrow">${esc(inferredName(w,i))}</div><label>Nom de la séance<input class="pe-day-name" value="${esc(w.name||inferredName(w,i))}"></label></div><button class="btn ghost pe-delete-day" data-day="${i}">SUPPRIMER</button></div><div class="pe-exercises">${(w.exercises||[]).map((raw,ei)=>exerciseHTML(norm(raw),i,ei)).join('')}</div><button class="btn pe-add-ex" data-day="${i}">+ AJOUTER UN EXERCICE</button></section>`}
function exerciseHTML(ex,wi,ei){const timed=ex.unit==='sec',m=libMatch(ex.name),custom=!m;const options=library().map(x=>`<option value="${esc(x.name)}" ${m?.name===x.name?'selected':''}>${esc(x.group)} — ${esc(x.name)}</option>`).join('');return `<div class="pe-exercise ${custom?'is-custom':'is-library'}" data-ex="${ei}"><div class="pe-source"><label>Exercice<select class="pe-library"><option value="__custom" ${custom?'selected':''}>✎ Choix libre</option>${options}</select></label>${custom?'<span class="pe-lib-badge">Fiche générique</span>':'<span class="pe-lib-badge">✓ Fiche technique + anatomie</span>'}</div><div class="pe-ex-title"><input class="pe-name" value="${esc(ex.name)}" ${custom?'':'readonly'} aria-label="Nom exercice"><button class="pe-remove" title="Supprimer">×</button></div><div class="pe-grid"><label>Séries<input class="pe-sets" type="number" min="1" max="10" value="${ex.sets}"></label><label>${timed?'Min (s)':'Reps min'}<input class="pe-min" type="number" min="1" value="${ex.repMin}"></label><label>${timed?'Objectif (s)':'Reps max'}<input class="pe-max" type="number" min="1" value="${ex.repMax}"></label><label>RPE<input class="pe-rpe" type="number" min="1" max="10" step="0.5" value="${ex.targetRpe}"></label><label>Repos<input class="pe-rest" type="number" min="0" step="5" value="${ex.restSeconds}"></label><label>Type<select class="pe-unit"><option value="reps" ${!timed?'selected':''}>Reps</option><option value="sec" ${timed?'selected':''}>Chrono</option></select></label></div></div>`}
function mount(){injectEditorStyle();const screen=$('#profileScreen'),box=$('#profileBox');if(!screen||!box||editing)return;const tab=$('[data-tab="program"]');if(!tab)return;if(!$('#programEditTab')){const b=document.createElement('button');b.className='chip';b.id='programEditTab';b.textContent='Modifier programme';tab.after(b);b.onclick=()=>openEditor(b)}}
function openEditor(button){injectEditorStyle();editing=true;$$('.profile-tabs .chip').forEach(x=>x.classList.remove('on'));button?.classList.add('on');const box=$('#profileBox');if(!box)return;box.innerHTML=editorHTML();bindEditor()}
function captureVisible(){const day=$('.program-day');if(!day||!draft[selectedDay])return;const w=draft[selectedDay];w.name=day.querySelector('.pe-day-name')?.value.trim()||inferredName(w,selectedDay);w.exercises=[...day.querySelectorAll('.pe-exercise')].map(row=>{let min=Math.max(1,Number(row.querySelector('.pe-min')?.value)||1),max=Math.max(1,Number(row.querySelector('.pe-max')?.value)||min);if(max<min)[min,max]=[max,min];return{name:row.querySelector('.pe-name')?.value.trim()||'Exercice',sets:Math.max(1,Number(row.querySelector('.pe-sets')?.value)||3),repMin:min,repMax:max,targetRpe:Math.min(10,Math.max(1,Number(row.querySelector('.pe-rpe')?.value)||8)),restSeconds:Math.max(0,Number(row.querySelector('.pe-rest')?.value)||0),unit:row.querySelector('.pe-unit')?.value==='sec'?'sec':'reps'}})}
function refreshDay(){const host=$('#peDayHost');if(host){host.innerHTML=dayHTML(selectedDay);bindDay()};const sel=$('#peDaySelect');if(sel){sel.innerHTML=draft.map((w,i)=>`<option value="${i}" ${i===selectedDay?'selected':''}>${esc(w.name||inferredName(w,i))}</option>`).join('')}}
function bindDay(){
  $$('.pe-remove').forEach(b=>b.onclick=()=>{b.closest('.pe-exercise')?.remove();captureVisible();draft[selectedDay].name=inferredName(draft[selectedDay],selectedDay);refreshDay()});
  $$('.pe-library').forEach(sel=>sel.onchange=()=>{const row=sel.closest('.pe-exercise');if(!row)return;const currentIndex=[...row.parentElement.children].indexOf(row);captureVisible();if(sel.value==='__custom'){draft[selectedDay].exercises[currentIndex]={...draft[selectedDay].exercises[currentIndex],name:'Nouvel exercice'}}else{const old=draft[selectedDay].exercises[currentIndex],base=norm(sel.value);draft[selectedDay].exercises[currentIndex]={...base,sets:old.sets,repMin:old.repMin,repMax:old.repMax,targetRpe:old.targetRpe,restSeconds:old.restSeconds,unit:old.unit,name:sel.value}}draft[selectedDay].name=inferredName(draft[selectedDay],selectedDay);refreshDay()});
  $('.pe-add-ex')?.addEventListener('click',()=>{captureVisible();draft[selectedDay].exercises.push(norm('Nouvel exercice'));refreshDay()});
  $('.pe-delete-day')?.addEventListener('click',()=>{captureVisible();if(draft.length<=1)return alert('Le programme doit garder au moins une séance.');draft.splice(selectedDay,1);selectedDay=Math.max(0,Math.min(selectedDay,draft.length-1));autoNameAll();refreshDay()});
  $('.pe-day-name')?.addEventListener('change',captureVisible);
  $$('.pe-name,.pe-sets,.pe-min,.pe-max,.pe-rpe,.pe-rest,.pe-unit').forEach(x=>x.addEventListener('change',()=>{captureVisible();draft[selectedDay].name=inferredName(draft[selectedDay],selectedDay);refreshDay()}));
}
function bindEditor(){$('#peDaySelect')?.addEventListener('change',e=>{captureVisible();selectedDay=Number(e.target.value)||0;refreshDay()});$('.pe-add-day')?.addEventListener('click',()=>{captureVisible();draft.push({name:'Nouvelle séance',exercises:[norm('Nouvel exercice')]});selectedDay=draft.length-1;draft[selectedDay].name=inferredName(draft[selectedDay],selectedDay);refreshDay()});$('.pe-save')?.addEventListener('click',saveEditor);bindDay()}
function saveEditor(){captureVisible();autoNameAll();const out=draft.filter(w=>Array.isArray(w.exercises)&&w.exercises.length).map((w,i)=>({...w,name:inferredName(w,i)}));if(!out.length)return alert('Ajoute au moins une séance avec un exercice.');const db=read();db.program=out;db.programSchema=2;write(db);window.dispatchEvent(new CustomEvent('onyx:program-created'));draft=out;refreshDay();const b=$('.pe-save');if(b){b.textContent='✓ PROGRAMME ENREGISTRÉ';setTimeout(()=>b.textContent='ENREGISTRER LE PROGRAMME',1600)}}
const obs=new MutationObserver(()=>{if(!editing)mount();if(editing&&!$('#profileScreen'))editing=false});obs.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('DOMContentLoaded',()=>setTimeout(mount,120));setTimeout(mount,250);
