// ONYX FIT v0.1 — advanced program editor
const STORAGE='onyx_v01';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')||{}}catch{return{}}};
const write=db=>localStorage.setItem(STORAGE,JSON.stringify(db));
const norm=ex=>window.OnyxProgram?.normalizeExercise?window.OnyxProgram.normalizeExercise(ex):{name:typeof ex==='string'?ex:(ex?.name||'Exercice'),sets:Number(ex?.sets)||3,repMin:Number(ex?.repMin)||8,repMax:Number(ex?.repMax)||12,targetRpe:Number(ex?.targetRpe)||8,restSeconds:Number(ex?.restSeconds)||60,unit:ex?.unit||'reps'};
let editing=false;
function program(){const db=read();return Array.isArray(db.program)?db.program:[]}
function editorHTML(){const p=program();return `<div class="card program-editor-card"><div class="program-editor-head"><div><div class="eyebrow">PROGRAMME ACTUEL</div><h2>Modifier mon programme</h2><p class="muted">Chaque exercice peut être réglé précisément. Les changements sont utilisés dès la prochaine séance.</p></div></div>${p.length?`<div class="program-editor-list">${p.map((w,wi)=>`<section class="program-day" data-day="${wi}"><div class="program-day-head"><label>Nom de la séance<input class="pe-day-name" value="${esc(w?.name||`Séance ${wi+1}`)}"></label><button class="btn ghost pe-delete-day" data-day="${wi}">SUPPRIMER</button></div><div class="pe-exercises">${(Array.isArray(w?.exercises)?w.exercises:[]).map((raw,ei)=>exerciseHTML(norm(raw),wi,ei)).join('')}</div><button class="btn pe-add-ex" data-day="${wi}">+ AJOUTER UN EXERCICE</button></section>`).join('')}</div><button class="btn pe-add-day full">+ AJOUTER UNE SÉANCE</button><button class="btn primary big full pe-save">ENREGISTRER LE PROGRAMME</button>`:`<p class="muted">Aucun programme. Crée d’abord un programme automatique puis personnalise-le ici.</p>`}</div>`}
function exerciseHTML(ex,wi,ei){const timed=ex.unit==='sec';return `<div class="pe-exercise" data-ex="${ei}"><div class="pe-ex-title"><input class="pe-name" value="${esc(ex.name)}" aria-label="Nom exercice"><button class="pe-remove" title="Supprimer">×</button></div><div class="pe-grid"><label>Séries<input class="pe-sets" type="number" min="1" max="10" value="${ex.sets}"></label><label>${timed?'Minimum (s)':'Reps min'}<input class="pe-min" type="number" min="1" value="${ex.repMin}"></label><label>${timed?'Objectif (s)':'Reps max'}<input class="pe-max" type="number" min="1" value="${ex.repMax}"></label><label>RPE cible<input class="pe-rpe" type="number" min="1" max="10" step="0.5" value="${ex.targetRpe}"></label><label>Repos (s)<input class="pe-rest" type="number" min="0" step="5" value="${ex.restSeconds}"></label><label>Type<select class="pe-unit"><option value="reps" ${!timed?'selected':''}>Répétitions</option><option value="sec" ${timed?'selected':''}>Chronométré</option></select></label></div></div>`}
function mount(){const screen=$('#profileScreen'),box=$('#profileBox');if(!screen||!box||editing)return;const tab=$('[data-tab="program"]');if(!tab)return;if(!$('#programEditTab')){const b=document.createElement('button');b.className='chip';b.id='programEditTab';b.textContent='Modifier programme';tab.after(b);b.onclick=()=>openEditor(b)} }
function openEditor(button){editing=true;$$('.profile-tabs .chip').forEach(x=>x.classList.remove('on'));button?.classList.add('on');const box=$('#profileBox');if(!box)return;box.innerHTML=editorHTML();bindEditor()}
function bindEditor(){
  $$('.pe-remove').forEach(b=>b.onclick=()=>b.closest('.pe-exercise')?.remove());
  $$('.pe-add-ex').forEach(b=>b.onclick=()=>{const day=b.closest('.program-day'),list=day?.querySelector('.pe-exercises');if(!list)return;const d=document.createElement('div');d.innerHTML=exerciseHTML(norm('Nouvel exercice'),Number(day.dataset.day),list.children.length);list.appendChild(d.firstElementChild);bindEditor()});
  $$('.pe-delete-day').forEach(b=>b.onclick=()=>{if(program().length<=1)return alert('Le programme doit garder au moins une séance.');b.closest('.program-day')?.remove()});
  $('.pe-add-day')?.addEventListener('click',()=>{const list=$('.program-editor-list');if(!list)return;const sec=document.createElement('section');sec.className='program-day';sec.dataset.day=list.children.length;sec.innerHTML=`<div class="program-day-head"><label>Nom de la séance<input class="pe-day-name" value="Nouvelle séance"></label><button class="btn ghost pe-delete-day">SUPPRIMER</button></div><div class="pe-exercises">${exerciseHTML(norm('Nouvel exercice'),list.children.length,0)}</div><button class="btn pe-add-ex">+ AJOUTER UN EXERCICE</button>`;list.appendChild(sec);bindEditor()});
  $('.pe-save')?.addEventListener('click',saveEditor);
}
function saveEditor(){const days=$$('.program-day');const out=days.map((day,di)=>({name:day.querySelector('.pe-day-name')?.value.trim()||`Séance ${di+1}`,exercises:[...day.querySelectorAll('.pe-exercise')].map(row=>{let min=Math.max(1,Number(row.querySelector('.pe-min')?.value)||1),max=Math.max(1,Number(row.querySelector('.pe-max')?.value)||min);if(max<min)[min,max]=[max,min];return{name:row.querySelector('.pe-name')?.value.trim()||'Exercice',sets:Math.max(1,Number(row.querySelector('.pe-sets')?.value)||3),repMin:min,repMax:max,targetRpe:Math.min(10,Math.max(1,Number(row.querySelector('.pe-rpe')?.value)||8)),restSeconds:Math.max(0,Number(row.querySelector('.pe-rest')?.value)||0),unit:row.querySelector('.pe-unit')?.value==='sec'?'sec':'reps'}}).filter(x=>x.name)})).filter(x=>x.exercises.length);if(!out.length)return alert('Ajoute au moins une séance avec un exercice.');const db=read();db.program=out;db.programSchema=2;write(db);window.dispatchEvent(new CustomEvent('onyx:program-created'));const b=$('.pe-save');if(b){b.textContent='✓ PROGRAMME ENREGISTRÉ';setTimeout(()=>b.textContent='ENREGISTRER LE PROGRAMME',1600)}}
const obs=new MutationObserver(()=>{if(!editing)mount();if(editing&&!$('#profileScreen'))editing=false});obs.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('DOMContentLoaded',()=>setTimeout(mount,120));setTimeout(mount,250);
