// ONYX FIT v0.1 — compact advanced program editor
const STORAGE='onyx_v01';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const read=()=>{try{return JSON.parse(localStorage.getItem(STORAGE)||'{}')||{}}catch{return{}}};
const write=db=>localStorage.setItem(STORAGE,JSON.stringify(db));
const norm=ex=>window.OnyxProgram?.normalizeExercise?window.OnyxProgram.normalizeExercise(ex):{name:typeof ex==='string'?ex:(ex?.name||'Exercice'),sets:Number(ex?.sets)||3,repMin:Number(ex?.repMin)||8,repMax:Number(ex?.repMax)||12,targetRpe:Number(ex?.targetRpe)||8,restSeconds:Number(ex?.restSeconds)||60,unit:ex?.unit||'reps'};
let editing=false,selectedDay=0,draft=[];
function program(){const db=read();return Array.isArray(db.program)?db.program:[]}
function cloneProgram(){return program().map((w,i)=>({name:w?.name||`Séance ${i+1}`,exercises:(Array.isArray(w?.exercises)?w.exercises:[]).map(norm)}))}
function groupScore(name){const n=String(name||'').toLowerCase();const s={Pecs:0,Dos:0,Épaules:0,Biceps:0,Triceps:0,Jambes:0,Fessiers:0,Abdos:0};
  if(/développé couché|developpe couche|développé incliné|developpe incline|pompe|pec|chest|écarté|ecarte/.test(n))s.Pecs+=3;
  if(/rowing|tirage|traction|pulldown|dors|dos|face pull/.test(n))s.Dos+=3;
  if(/épaule|epaule|élévation|elevation|oiseau|militaire|shoulder|face pull/.test(n))s.Épaules+=2;
  if(/curl|biceps/.test(n))s.Biceps+=3;
  if(/triceps|extension triceps|barre au front|dips/.test(n))s.Triceps+=3;
  if(/squat|fente|bulgare|leg press|leg extension|leg curl|mollet|soulevé de terre|souleve de terre/.test(n))s.Jambes+=3;
  if(/hip thrust|fessier|glute|bulgare/.test(n))s.Fessiers+=2;
  if(/abdo|planche|gainage|crunch/.test(n))s.Abdo+=3;
  return s;
}
function inferredName(w,idx){const totals={Pecs:0,Dos:0,Épaules:0,Biceps:0,Triceps:0,Jambes:0,Fessiers:0,Abdos:0};(w?.exercises||[]).forEach(ex=>{const sc=groupScore(ex?.name||ex);Object.keys(totals).forEach(k=>totals[k]+=sc[k]||0)});const ranked=Object.entries(totals).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]);if(!ranked.length)return `Séance ${idx+1}`;const a=ranked[0]?.[0],b=ranked[1]?.[0];const pair=(a==='Pecs'&&b==='Triceps')||(a==='Triceps'&&b==='Pecs')?'Pecs / Triceps':(a==='Dos'&&b==='Biceps')||(a==='Biceps'&&b==='Dos')?'Dos / Biceps':(a==='Jambes'&&b==='Fessiers')||(a==='Fessiers'&&b==='Jambes')?'Jambes / Fessiers':b&&ranked[1][1]>=Math.max(2,ranked[0][1]*.45)?`${a} / ${b}`:a;return pair}
function autoNameAll(){draft.forEach((w,i)=>{w.name=inferredName(w,i)})}
function editorHTML(){draft=cloneProgram();autoNameAll();selectedDay=Math.min(selectedDay,Math.max(0,draft.length-1));return `<div class="card program-editor-card"><div class="program-editor-head"><div><div class="eyebrow">PROGRAMME ACTUEL</div><h2>Modifier mon programme</h2><p class="muted">Choisis une séance à modifier. Le nom est basé sur les groupes musculaires les plus travaillés.</p></div></div>${draft.length?`<label>SEANCE A MODIFIER<select id="peDaySelect">${draft.map((w,i)=>`<option value="${i}" ${i===selectedDay?'selected':''}>${esc(w.name||inferredName(w,i))}</option>`).join('')}</select></label><div id="peDayHost">${dayHTML(selectedDay)}</div><button class="btn pe-add-day full">+ AJOUTER UNE SÉANCE</button><button class="btn primary big full pe-save">ENREGISTRER LE PROGRAMME</button>`:`<p class="muted">Aucun programme. Crée d’abord un programme automatique puis personnalise-le ici.</p>`}</div>`}
function dayHTML(i){const w=draft[i];if(!w)return'';return `<section class="program-day" data-day="${i}"><div class="program-day-head"><div><div class="eyebrow">${esc(inferredName(w,i))}</div><label>Nom de la séance<input class="pe-day-name" value="${esc(w.name||inferredName(w,i))}"></label></div><button class="btn ghost pe-delete-day" data-day="${i}">SUPPRIMER</button></div><div class="pe-exercises">${(w.exercises||[]).map((raw,ei)=>exerciseHTML(norm(raw),i,ei)).join('')}</div><button class="btn pe-add-ex" data-day="${i}">+ AJOUTER UN EXERCICE</button></section>`}
function exerciseHTML(ex,wi,ei){const timed=ex.unit==='sec';return `<div class="pe-exercise" data-ex="${ei}"><div class="pe-ex-title"><input class="pe-name" value="${esc(ex.name)}" aria-label="Nom exercice"><button class="pe-remove" title="Supprimer">×</button></div><div class="pe-grid"><label>Séries<input class="pe-sets" type="number" min="1" max="10" value="${ex.sets}"></label><label>${timed?'Minimum (s)':'Reps min'}<input class="pe-min" type="number" min="1" value="${ex.repMin}"></label><label>${timed?'Objectif (s)':'Reps max'}<input class="pe-max" type="number" min="1" value="${ex.repMax}"></label><label>RPE cible<input class="pe-rpe" type="number" min="1" max="10" step="0.5" value="${ex.targetRpe}"></label><label>Repos (s)<input class="pe-rest" type="number" min="0" step="5" value="${ex.restSeconds}"></label><label>Type<select class="pe-unit"><option value="reps" ${!timed?'selected':''}>Répétitions</option><option value="sec" ${timed?'selected':''}>Chronométré</option></select></label></div></div>`}
function mount(){const screen=$('#profileScreen'),box=$('#profileBox');if(!screen||!box||editing)return;const tab=$('[data-tab="program"]');if(!tab)return;if(!$('#programEditTab')){const b=document.createElement('button');b.className='chip';b.id='programEditTab';b.textContent='Modifier programme';tab.after(b);b.onclick=()=>openEditor(b)}}
function openEditor(button){editing=true;$$('.profile-tabs .chip').forEach(x=>x.classList.remove('on'));button?.classList.add('on');const box=$('#profileBox');if(!box)return;box.innerHTML=editorHTML();bindEditor()}
function captureVisible(){const day=$('.program-day');if(!day||!draft[selectedDay])return;const w=draft[selectedDay];w.name=day.querySelector('.pe-day-name')?.value.trim()||inferredName(w,selectedDay);w.exercises=[...day.querySelectorAll('.pe-exercise')].map(row=>{let min=Math.max(1,Number(row.querySelector('.pe-min')?.value)||1),max=Math.max(1,Number(row.querySelector('.pe-max')?.value)||min);if(max<min)[min,max]=[max,min];return{name:row.querySelector('.pe-name')?.value.trim()||'Exercice',sets:Math.max(1,Number(row.querySelector('.pe-sets')?.value)||3),repMin:min,repMax:max,targetRpe:Math.min(10,Math.max(1,Number(row.querySelector('.pe-rpe')?.value)||8)),restSeconds:Math.max(0,Number(row.querySelector('.pe-rest')?.value)||0),unit:row.querySelector('.pe-unit')?.value==='sec'?'sec':'reps'}})}
function refreshDay(){const host=$('#peDayHost');if(host){host.innerHTML=dayHTML(selectedDay);bindDay()};const sel=$('#peDaySelect');if(sel){sel.innerHTML=draft.map((w,i)=>`<option value="${i}" ${i===selectedDay?'selected':''}>${esc(w.name||inferredName(w,i))}</option>`).join('')}}
function bindDay(){
  $$('.pe-remove').forEach(b=>b.onclick=()=>{b.closest('.pe-exercise')?.remove();captureVisible();const w=draft[selectedDay];w.name=inferredName(w,selectedDay);refreshDay()});
  $('.pe-add-ex')?.addEventListener('click',()=>{captureVisible();draft[selectedDay].exercises.push(norm('Nouvel exercice'));refreshDay()});
  $('.pe-delete-day')?.addEventListener('click',()=>{captureVisible();if(draft.length<=1)return alert('Le programme doit garder au moins une séance.');draft.splice(selectedDay,1);selectedDay=Math.max(0,Math.min(selectedDay,draft.length-1));autoNameAll();refreshDay()});
  $('.pe-day-name')?.addEventListener('change',captureVisible);
  $$('.pe-name,.pe-sets,.pe-min,.pe-max,.pe-rpe,.pe-rest,.pe-unit').forEach(x=>x.addEventListener('change',()=>{captureVisible();const w=draft[selectedDay];w.name=inferredName(w,selectedDay);refreshDay()}));
}
function bindEditor(){
  $('#peDaySelect')?.addEventListener('change',e=>{captureVisible();selectedDay=Number(e.target.value)||0;refreshDay()});
  $('.pe-add-day')?.addEventListener('click',()=>{captureVisible();draft.push({name:'Nouvelle séance',exercises:[norm('Nouvel exercice')]});selectedDay=draft.length-1;draft[selectedDay].name=inferredName(draft[selectedDay],selectedDay);refreshDay()});
  $('.pe-save')?.addEventListener('click',saveEditor);bindDay();
}
function saveEditor(){captureVisible();autoNameAll();const out=draft.filter(w=>Array.isArray(w.exercises)&&w.exercises.length).map((w,i)=>({...w,name:inferredName(w,i)}));if(!out.length)return alert('Ajoute au moins une séance avec un exercice.');const db=read();db.program=out;db.programSchema=2;write(db);window.dispatchEvent(new CustomEvent('onyx:program-created'));draft=out;refreshDay();const b=$('.pe-save');if(b){b.textContent='✓ PROGRAMME ENREGISTRÉ';setTimeout(()=>b.textContent='ENREGISTRER LE PROGRAMME',1600)}}
const obs=new MutationObserver(()=>{if(!editing)mount();if(editing&&!$('#profileScreen'))editing=false});obs.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('DOMContentLoaded',()=>setTimeout(mount,120));setTimeout(mount,250);
